<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add Watch Location</name>
   <tag></tag>
   <elementGuidId>acd171ea-e2e8-4107-a834-0bcd469f14d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.k-button.k-button-md.k-rounded-md.k-button-solid.k-button-solid-base.k-toolbar-button.k-grid-add-watch-location.k-grid-addwatchlocation.k-toolbar-tool.k-focus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bc184c51-f609-4101-ab38-98bceb3e4a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-button k-button-md k-rounded-md k-button-solid k-button-solid-base k-toolbar-button k-grid-add-watch-location k-grid-addwatchlocation k-toolbar-tool k-focus</value>
      <webElementGuid>e79df550-d6dd-4fa4-9ed0-6756380087ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cd3f0e08-5784-454a-9318-b3a4ab463ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>56ec90d7-fb2e-4a97-a826-d27c0954692c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6b092f0b-18e9-4980-bdfc-c9e92573c388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>816984ad-41b6-44fd-8b04-5158a0278328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uid</name>
      <type>Main</type>
      <value>f4519cb1-614c-4acb-b1b5-d4ba18e575ac</value>
      <webElementGuid>d84073bb-af00-4fac-a36b-1228b07a4932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Watch Location</value>
      <webElementGuid>eb15f81c-12c3-45eb-9762-6732a1cdd7e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WatchLocationGrid&quot;)/div[@class=&quot;k-grid-toolbar k-toolbar k-toolbar-resizable k-toolbar-md&quot;]/button[@class=&quot;k-button k-button-md k-rounded-md k-button-solid k-button-solid-base k-toolbar-button k-grid-add-watch-location k-grid-addwatchlocation k-toolbar-tool k-focus&quot;]</value>
      <webElementGuid>2042e279-1158-43c3-89fb-7b1bb404cdf6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[7]</value>
      <webElementGuid>cabfb8e5-21c6-4ea9-a372-c88fb4aeeb44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='WatchLocationGrid']/div/button</value>
      <webElementGuid>eeda7073-6fbe-4a24-b05a-9e9a5bd8e651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/following::button[1]</value>
      <webElementGuid>279dbd9d-b087-410a-b2c5-be3cb0b7313b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::button[2]</value>
      <webElementGuid>5399ed97-d0f9-4d7a-a2c4-73f401ec2c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Watch Location'])[1]/preceding::button[2]</value>
      <webElementGuid>9b8abc8e-585d-407e-baab-5e02d0a8ea83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/div/div/button</value>
      <webElementGuid>bd2909b3-a517-4015-beb6-f8b723b9eaa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Add Watch Location' or . = 'Add Watch Location')]</value>
      <webElementGuid>20a88036-3345-4474-831a-ead6dd5bd2f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
