<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add Location</name>
   <tag></tag>
   <elementGuidId>4231d2e2-6098-43df-b275-750abd136b8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[normalize-space()='Add Location']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.k-button.k-button-md.k-rounded-md.k-button-solid.k-button-solid-base.k-toolbar-button.k-grid-add-location.k-grid-addlocation.k-toolbar-tool.k-focus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>611d6825-e12a-417d-b4d5-10ea91cad96a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-button k-button-md k-rounded-md k-button-solid k-button-solid-base k-toolbar-button k-grid-add-location k-grid-addlocation k-toolbar-tool k-focus</value>
      <webElementGuid>a61f6d73-a1b3-4157-b67e-af6f8f229d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b8a88acc-9b93-4170-8a0f-73cfd53039df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3beceb00-2e2e-4015-be6e-fa1fd3a3502e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ce40f0ba-28e3-4e9e-8921-996acf4fa255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>485206ee-d1d5-4323-9f6b-6063501bdb45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uid</name>
      <type>Main</type>
      <value>a92faeda-4981-43ad-acef-d15e4b5fcf85</value>
      <webElementGuid>49fee4a5-26dd-482f-804e-f431493d4121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Location</value>
      <webElementGuid>8be215ea-d303-4f6b-9cb5-2a63ffa23148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CustomerLocationGrid&quot;)/div[@class=&quot;k-grid-toolbar k-toolbar k-toolbar-resizable k-toolbar-md&quot;]/button[@class=&quot;k-button k-button-md k-rounded-md k-button-solid k-button-solid-base k-toolbar-button k-grid-add-location k-grid-addlocation k-toolbar-tool k-focus&quot;]</value>
      <webElementGuid>871c7bbf-5530-43dd-bec9-52ecc179bf19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>9f18d6a4-b056-451d-9d79-b94c373c9f4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CustomerLocationGrid']/div/button</value>
      <webElementGuid>9a6b36c6-408c-4f78-b3e6-8e2b79bddd5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to List'])[1]/following::button[1]</value>
      <webElementGuid>e0a0d2b7-aa91-47d0-9970-19e28487363c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>274c983e-aabc-4ce0-a612-57e5b775ad97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Location'])[1]/preceding::button[2]</value>
      <webElementGuid>d1d0db05-a5e8-4b2b-aa19-c24ab3196bdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>01b22fda-0a7e-4fbd-b407-775a6abe7ddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Add Location' or . = 'Add Location')]</value>
      <webElementGuid>7e9b6694-2817-4702-9030-0673d2a7c2d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
