<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add Move Location</name>
   <tag></tag>
   <elementGuidId>0a067a98-aa3f-413f-8070-e3beb887192a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.k-button.k-button-md.k-rounded-md.k-button-solid.k-button-solid-base.k-toolbar-button.k-grid-add-move-location.k-grid-addmovelocation.k-toolbar-tool.k-focus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[normalize-space()='Add Move Location']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ae7ec27b-4104-434f-8c6a-a42fd0c0e478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-button k-button-md k-rounded-md k-button-solid k-button-solid-base k-toolbar-button k-grid-add-move-location k-grid-addmovelocation k-toolbar-tool k-focus</value>
      <webElementGuid>66f537a0-0200-4b7b-9db7-27125370e7b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>441f9a1f-7039-4f83-b2ae-f62811a24177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>623ff4b2-31a9-4241-9084-e0716abbdc1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cc2a0a55-c8e9-4e83-b5ce-2c95343117c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7ccf9216-1b9d-4aec-87ee-8f7ae2a212cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uid</name>
      <type>Main</type>
      <value>cd0fdaf9-9e2c-4bdf-b541-7340981abbd6</value>
      <webElementGuid>73946b8f-ccba-41be-b6e3-50f76d0da188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Move Location</value>
      <webElementGuid>b8ebc211-8320-44a6-98bd-f79723ab7097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MoveLocationGrid&quot;)/div[@class=&quot;k-grid-toolbar k-toolbar k-toolbar-resizable k-toolbar-md&quot;]/button[@class=&quot;k-button k-button-md k-rounded-md k-button-solid k-button-solid-base k-toolbar-button k-grid-add-move-location k-grid-addmovelocation k-toolbar-tool k-focus&quot;]</value>
      <webElementGuid>46500c81-2939-4c61-ab77-ce6663dd5c70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[11]</value>
      <webElementGuid>ccd7f715-8a13-4101-94ec-4abc354f2ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MoveLocationGrid']/div/button</value>
      <webElementGuid>934d7b8e-e4a0-48a6-9908-647be38b5496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[2]/following::button[6]</value>
      <webElementGuid>7d9c72ae-6f9b-4119-986a-897bbfb54d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[2]/following::button[7]</value>
      <webElementGuid>24be83ea-d32e-4205-a0e3-880f220a144a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move Location'])[1]/preceding::button[2]</value>
      <webElementGuid>b16e3534-3876-4250-8972-3906e5e08c7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/div/div/button</value>
      <webElementGuid>3164b92c-9a40-4967-b48b-df4c69d321de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Add Move Location' or . = 'Add Move Location')]</value>
      <webElementGuid>473facf6-440e-40f9-873e-31ab8f8999b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
