<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TEC Location_TECLocation</name>
   <tag></tag>
   <elementGuidId>c9eb53fe-17df-4db9-b552-a787ad8538f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TECLocation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TECLocation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7100e143-88e7-46ac-8c44-811c7bccd0df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c2736847-72a0-44bd-94dd-bfab11a65e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TECLocation</value>
      <webElementGuid>d1244152-cee7-494d-ba2a-e2daa4bac79c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TECLocation</value>
      <webElementGuid>72b70275-0556-4d55-a41a-a07e3f9c6592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>e160c3ac-e9a3-4243-a16a-63812295622d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>333f2d4c-ab35-4b94-b8a9-6b44296eecb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TECLocation&quot;)</value>
      <webElementGuid>159966ea-8cdc-47d9-9f62-c22b41900cfa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TECLocation']</value>
      <webElementGuid>0ffe595e-eaea-4fd5-bf07-71235307b4d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmCustomerLocation']/div[2]/div[2]/input</value>
      <webElementGuid>7613dfed-71c5-44ee-acd5-a7a896912bbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>ad00e28a-ac61-4b67-9d6c-2685356ba157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TECLocation' and @name = 'TECLocation' and @type = 'text']</value>
      <webElementGuid>711f8c70-f089-43a5-806c-bb51f3e70589</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
