<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Prophet21ID_Prophet21ID</name>
   <tag></tag>
   <elementGuidId>d765a2e4-5e2f-443f-aa23-8b34dd6d8f28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Prophet21ID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Prophet21ID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d61994f3-218f-4c55-a35d-e2d57b163ff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>294ff08b-2322-4ff6-9cbc-8999adb7711b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>52fa1338-1a73-449f-99b6-755628277dba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>df2103a9-7e90-4d61-a2ae-4487c4af18b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Prophet21ID field is required.</value>
      <webElementGuid>d8b3a877-63ea-4b82-afb1-49eaed63a759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Prophet21ID</value>
      <webElementGuid>f0d7b295-8f0b-47b8-9669-696478520d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Prophet21ID</value>
      <webElementGuid>2767d0dd-85c7-4846-9c27-3c112f3d7b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Prophet21ID&quot;)</value>
      <webElementGuid>accafa98-c915-4614-8283-d988507baf99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Prophet21ID']</value>
      <webElementGuid>7571abe2-d797-406b-909a-8b3ae30da3e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='CreateImportCustomerForm']/div[2]/input</value>
      <webElementGuid>20af777f-e431-4f16-9613-11a6334773d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>26421b0d-08eb-43cc-a93a-5bdeba588e87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'Prophet21ID' and @name = 'Prophet21ID']</value>
      <webElementGuid>19eaf530-073c-43ec-9162-bda9bb2fb091</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
