<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Move Location_MoveLocation</name>
   <tag></tag>
   <elementGuidId>b6a543b6-29c3-4ce1-b04b-fd45cfecb49c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MoveLocation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MoveLocation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>668693af-8a7b-4316-a39d-560d24b0e6b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>283da24c-38e5-4d6a-8697-e0244022d7c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3a2f4bfe-1ab2-4faa-ac1e-deb3be1bb999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The MoveLocation field is required.</value>
      <webElementGuid>79a888e5-cd79-4aaf-9860-82f6089bfaa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MoveLocation</value>
      <webElementGuid>d80d48bd-6580-4f35-a7e3-ecf1eea666e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MoveLocation</value>
      <webElementGuid>a1b52dac-e4e1-4c19-8325-3d2053f6c903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>2ba8562f-730d-4112-b220-b5fbaf2e8022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b6cad0c1-c24a-4ca0-be9c-caa8316cb4ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MoveLocation&quot;)</value>
      <webElementGuid>1aefdc52-9c6a-469e-867a-519f91219a76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MoveLocation']</value>
      <webElementGuid>f8e8badc-5c46-4aa8-a4f6-8da2b9daef1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmMoveLocation']/div[2]/div/input</value>
      <webElementGuid>f26924b1-164d-4e1f-ae5d-7ac3ae031310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>d51ef7e8-ab06-49b6-a6bd-1dd20664fd32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'MoveLocation' and @name = 'MoveLocation' and @type = 'text']</value>
      <webElementGuid>41ce2ac1-b877-448d-a410-002ac7232215</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
