<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Customer Location_CustomerLocation</name>
   <tag></tag>
   <elementGuidId>f46c6ec4-b17f-42e6-ab28-74b471e7a2fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CustomerLocation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CustomerLocation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>de530a2a-fbcf-4415-8322-054af5fba1d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>db0bde18-4d78-417e-ba78-eb906f23ab10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CustomerLocation</value>
      <webElementGuid>929a83db-45e1-4bf0-be1c-fd6a55d8fad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CustomerLocation</value>
      <webElementGuid>0ed036fa-8685-47f1-b517-0b06c2e7e5d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>3bcb8f41-06c2-442a-9c43-1df4603aa29f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6dd5fb98-e80b-4a49-a1aa-e40be24c886e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CustomerLocation&quot;)</value>
      <webElementGuid>64f5a74c-05b8-4342-a24b-d6d71892ae2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CustomerLocation']</value>
      <webElementGuid>a19b7cb0-39f2-4640-a943-f203dede3ab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmCustomerLocation']/div[2]/div/input</value>
      <webElementGuid>dcee4349-1f09-42c3-bdea-ccac6e14ce3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>8f7583aa-50f3-4593-a98c-718e420be850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CustomerLocation' and @name = 'CustomerLocation' and @type = 'text']</value>
      <webElementGuid>eaba5a29-cbb3-407c-b8e0-ede25b8980b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
