<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Notify Who_k-input-inner</name>
   <tag></tag>
   <elementGuidId>86645327-5af8-4000-9093-e5fa729521b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.k-input-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmWatchLocation']/div[2]/div[2]/div/span/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8cf3918c-6b24-4940-8be3-9dbebebdd10c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input-inner</value>
      <webElementGuid>f6df344e-8319-4c57-bb57-6d2e7566270c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b922a950-d62a-4557-84be-0a37605b9816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c5f3c939-c65c-4559-a6d5-d114a4cb7081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>3c9dc40d-7ae5-4770-aeab-3327429377a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>afef01cd-ae6c-48ca-b35f-48caa8fd9267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>NotifyWho_listbox</value>
      <webElementGuid>c608a3b6-8a0a-412c-bf60-6d0b0d94fd5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>b578e473-0111-4404-b6cf-4c7a33589afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>NotifyWho_taglist</value>
      <webElementGuid>7c6cf0b0-044d-454b-9fa0-458039d7162c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>NotifyWho_label</value>
      <webElementGuid>6f94184e-0a25-4270-a8d4-9444eeab8084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d57687bd-7d71-4056-b325-260b4df19e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>40929e03-1a7f-4556-a897-ea301f32c73d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-busy</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5fa3aa8b-035b-4ab6-97ba-fe1ff324f271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmWatchLocation&quot;)/div[@class=&quot;modal-body&quot;]/div[@class=&quot;form-group&quot;]/div[1]/span[@class=&quot;k-multiselect k-input k-multiselect-clearable k-input-solid k-input-md k-rounded-md k-focus&quot;]/div[@class=&quot;k-input-values&quot;]/input[@class=&quot;k-input-inner&quot;]</value>
      <webElementGuid>f29bb830-7edf-4f16-b047-ffc65b7dcec6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmWatchLocation']/div[2]/div[2]/div/span/div/input</value>
      <webElementGuid>6b611dac-8c6a-463a-a875-87dee3f2787f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/input</value>
      <webElementGuid>15abfde6-bdda-4a15-9292-6a3175500663</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
