<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Watch Location_WatchLocation</name>
   <tag></tag>
   <elementGuidId>d6d836df-f107-4340-857c-441669df5923</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#WatchLocation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='WatchLocation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2cf771e0-2802-47d4-a76e-315985ade8b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>43119370-4ec3-4b5b-8c0f-fe630844c24e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WatchLocation</value>
      <webElementGuid>a140c8cc-3c0a-4cc2-80b9-fc6f932ce03c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>WatchLocation</value>
      <webElementGuid>99a289d1-ea5f-497d-947c-ed42b32c0302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>6aa575b8-66ba-4bde-8483-91b948bdaeae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>45c0554f-686e-49e0-b1b5-6ffa5d36e36c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WatchLocation&quot;)</value>
      <webElementGuid>a757e7ef-d3b6-416f-809e-aa3ccf9a33e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='WatchLocation']</value>
      <webElementGuid>a2871944-aa84-4179-ae7e-6236531f4216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmWatchLocation']/div[2]/div/input</value>
      <webElementGuid>0e0901c0-daa3-43f9-aa09-51a37ecedf8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>b0d11132-a2d0-4a08-afcf-67ea3a9e0317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'WatchLocation' and @name = 'WatchLocation' and @type = 'text']</value>
      <webElementGuid>86c45121-614d-418b-8908-9cac3cefe777</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
