<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>ScrollAutoLineNumber_label</description>
   <name>ScrollAutoLineNumber_label</name>
   <tag></tag>
   <elementGuidId>5b6eef40-cbc6-4b73-8fb9-ccc469f78ad6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='AutoLineNumber_label']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
