<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_account_circle</name>
   <tag></tag>
   <elementGuidId>946b29f5-b243-4dee-a119-73eb327fbfc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-bar-section']/div/div[2]/ul/li[3]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.user-profile-icon.show > i.material-icons</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a9008a00-7fef-4804-b0f8-ed4b9ebcf56a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons</value>
      <webElementGuid>52376b1c-8103-4bf2-97b4-1947ab114879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>account_circle</value>
      <webElementGuid>730f1233-9b83-41de-991d-097beca1005d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-bar-section&quot;)/div[@class=&quot;page-header-inner&quot;]/div[@class=&quot;top-menu&quot;]/ul[@class=&quot;nav navbar-nav pull-right&quot;]/li[@class=&quot;dropdown dropdown-user&quot;]/a[@class=&quot;user-profile-icon show&quot;]/i[@class=&quot;material-icons&quot;]</value>
      <webElementGuid>503239d2-5ad5-4058-b4ad-aafce91e38e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-bar-section']/div/div[2]/ul/li[3]/a/i</value>
      <webElementGuid>ad0c16c7-e47d-4dba-8cd0-521f9ec33c18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All notifications'])[1]/following::i[1]</value>
      <webElementGuid>d8115027-356e-4048-ac93-1e3c96e14d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications'])[1]/following::i[1]</value>
      <webElementGuid>7c5e3ee0-b8dd-4d72-8f9b-16c289f26522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='account_box'])[1]/preceding::i[1]</value>
      <webElementGuid>8def93eb-12d3-43cb-ad73-980670dbf548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='account_circle']/parent::*</value>
      <webElementGuid>042e3ec7-260f-410f-b461-e683ccd03ef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[3]/a/i</value>
      <webElementGuid>a3b79fd0-2b9b-43da-8f9b-dc9c875ef1a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'account_circle' or . = 'account_circle')]</value>
      <webElementGuid>0a520426-624f-4c0d-9b1b-952b87689b88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
