<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_NO_k-switch-thumb k-rounded-full_1</name>
   <tag></tag>
   <elementGuidId>337846b1-55c2-48a8-aab5-7a94f1d55abe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='CreateImportCustomerForm']/div[7]/span/span[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.k-switch.k-switch-md.k-rounded-full.k-switch-off > span.k-switch-thumb-wrap > span.k-switch-thumb.k-rounded-full</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>73f70bc5-46f8-4570-8ad9-83da9005fbd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-switch-thumb k-rounded-full</value>
      <webElementGuid>6eebc2c7-cea6-4850-8d07-3015b8bad037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CreateImportCustomerForm&quot;)/div[@class=&quot;form-group&quot;]/span[@class=&quot;k-switch k-switch-md k-rounded-full k-switch-off&quot;]/span[@class=&quot;k-switch-thumb-wrap&quot;]/span[@class=&quot;k-switch-thumb k-rounded-full&quot;]</value>
      <webElementGuid>7f7608f9-fce8-426e-a9aa-c67df1ee8359</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='CreateImportCustomerForm']/div[7]/span/span[2]/span</value>
      <webElementGuid>ad2f2f03-4f3d-4957-be31-f0a3434196dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/span/span[2]/span</value>
      <webElementGuid>aac0b205-3898-471a-8bc7-1116e107a88c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
