<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_BOW01_k-list-item k-hover</name>
   <tag></tag>
   <elementGuidId>edc017fb-7cd0-472d-b223-8054a27d7dc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.k-list-item.k-hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='SelectedProphet21ID_listbox']/li[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;​WHA01&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>52084089-92d5-47dc-aa34-0a6fde98569a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>5cb8f211-28ab-40c7-afe5-224476e56167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>f003ec98-4363-4f70-b2e2-dc79a84c278b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>a2011511-12da-45a4-b15a-68193a5c92b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-list-item k-hover</value>
      <webElementGuid>cd85aa9e-d3e4-44a1-8b83-ba8957728a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>008d8827-7a0d-4c47-b9e8-bf0c4522fa34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-offset-index</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>426a1f5a-f644-4dd5-b04e-c0fb14fb3fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WHA01</value>
      <webElementGuid>5745a9a6-ddb4-4d4d-997e-13215ed490c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SelectedProphet21ID_listbox&quot;)/li[@class=&quot;k-list-item k-hover&quot;]</value>
      <webElementGuid>237bc53b-9d03-40b1-84f3-c8b56f173baf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='SelectedProphet21ID_listbox']/li[4]</value>
      <webElementGuid>87c16638-fd17-4e67-a047-64245789f004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BOW01'])[1]/following::li[1]</value>
      <webElementGuid>6f061825-7c17-4607-ab77-0b794d5e8aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LMR01'])[1]/following::li[2]</value>
      <webElementGuid>c0b033c3-b425-4b29-96d3-a9d729b9eedd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAN01'])[1]/preceding::li[1]</value>
      <webElementGuid>7591246f-1699-4fd2-89a5-3a955bbd6f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li[4]</value>
      <webElementGuid>73728639-304b-4bcc-b4a6-f7f073fb0b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'WHA01' or . = 'WHA01')]</value>
      <webElementGuid>a0abc9f4-67e0-4ece-a846-8c13660f1cdf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
