<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select Customer_k-input-value-text</name>
   <tag></tag>
   <elementGuidId>5ebb94ac-5ae7-4bb9-8f22-edbf324deeec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.k-input-value-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='acd6a684-f43c-4f87-aa24-4a9185793957']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#page-body-content >> internal:text=&quot;Select Customer...&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ece03297-6d07-4a82-b946-3750ec365107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input-value-text</value>
      <webElementGuid>d0ea1839-6128-4611-881c-d5e115a6726e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Customer...</value>
      <webElementGuid>114ba58c-fd91-494c-9779-ad712e382cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acd6a684-f43c-4f87-aa24-4a9185793957&quot;)/span[@class=&quot;k-input-value-text&quot;]</value>
      <webElementGuid>6c8a6a27-febf-4d3d-81a2-d9f19c1d25c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='acd6a684-f43c-4f87-aa24-4a9185793957']/span</value>
      <webElementGuid>bc7e28c4-2999-4823-a6ea-41a56d18fbd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Customer'])[1]/following::span[3]</value>
      <webElementGuid>7d4bf9eb-2e4f-4a6b-b3a2-41602d3410f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Environment Settings'])[1]/following::span[4]</value>
      <webElementGuid>e7f8117f-8694-4061-93f4-9ace9e73a9bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Location'])[1]/preceding::span[4]</value>
      <webElementGuid>c2657204-4849-437d-adf4-6b20b74d369f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Location...'])[1]/preceding::span[4]</value>
      <webElementGuid>aad8664d-8fd7-4e19-93d4-cdee5b70ce95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select Customer...']/parent::*</value>
      <webElementGuid>59755016-9d97-44b5-ad62-254260aba5ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span</value>
      <webElementGuid>ab91ff83-c629-4412-97be-bf97145a33a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Select Customer...' or . = 'Select Customer...')]</value>
      <webElementGuid>385c908c-92e4-4de2-a726-375f60639a82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
