<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Environment Settings_create-rule-btn</name>
   <tag></tag>
   <elementGuidId>a0b2d45c-39bc-44fa-96c8-dc419fc092b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.create-rule-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-body-content']/div[3]/div/div/div[2]/p/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Create New&quot;i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ea40c00e-495b-4e35-bb0c-07afdec9a842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>create-rule-btn</value>
      <webElementGuid>eabff4a6-91ab-4aed-917a-8c0c860e4ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-soptype</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>ffde68c0-9185-479c-a84c-f148142d3c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-prophet21id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>958a2692-0fe7-4dcb-96f7-d10f9c08f3fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create New</value>
      <webElementGuid>c45e2154-c5ec-469b-80ba-9743f735a451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-body-content&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;card card-box mb-4&quot;]/div[@class=&quot;card-body&quot;]/p[1]/a[@class=&quot;create-rule-btn&quot;]</value>
      <webElementGuid>df2a82ab-9783-4f3c-87da-16a4cfe6d337</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-body-content']/div[3]/div/div/div[2]/p/a</value>
      <webElementGuid>8d325f5e-eede-46d6-8891-cdfa5ebea088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Create New')]</value>
      <webElementGuid>52c1e83c-2f9c-41e2-a093-de8599bb99d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Environment Settings'])[1]/following::a[3]</value>
      <webElementGuid>c5ae30aa-4ab3-49a6-a93a-db088c1bcb9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Template'])[1]/following::a[4]</value>
      <webElementGuid>3c2a2399-b601-4274-8fe0-495d2b800dcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/preceding::a[1]</value>
      <webElementGuid>9da492d4-8f82-4dd7-ba60-173d97bc82d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/preceding::a[1]</value>
      <webElementGuid>f9346e17-d326-4692-bfd6-915d26e8b534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create New']/parent::*</value>
      <webElementGuid>4c3c1731-7d34-40cf-8e75-bd7bb5b69061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>d9d393ae-658a-4528-9032-b73d0a47163c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Create New' or . = 'Create New')]</value>
      <webElementGuid>cb1f40e9-2798-497e-a06b-75140246c508</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
