<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_items per page_create-rule-btn</name>
   <tag></tag>
   <elementGuidId>b186c0e2-7474-4e40-838e-e9db221a6eff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>html[1]/body[1]/div[1]/div[3]/div[2]/div[1]/div[3]/div[1]/div[1]/div[2]/p[1]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Create New&quot;i >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a117481d-31d2-4acb-9c87-1a8979413083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>create-rule-btn</value>
      <webElementGuid>d56a3da6-80fd-4ecf-89da-9605910ca7dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-soptype</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>a226b516-9cca-4156-ab43-1c39d14ef5dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-prophet21id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ccce501a-57d9-4e96-b689-6ce0ba72efd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create New</value>
      <webElementGuid>4ec7dff8-663d-44a2-a289-a6740e16b375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-body-content&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;card card-box&quot;]/div[@class=&quot;card-body&quot;]/p[1]/a[@class=&quot;create-rule-btn&quot;]</value>
      <webElementGuid>5ad3462b-f170-438a-90ce-697f869b9897</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-body-content']/div[3]/div/div[2]/div[2]/p/a</value>
      <webElementGuid>08682f97-d452-4806-b7a7-2b2120832807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Create New')])[2]</value>
      <webElementGuid>bcccec6e-6edd-42c6-9474-083242b122d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='items per page'])[1]/following::a[3]</value>
      <webElementGuid>e5bb2f9e-5b1b-43ae-b67e-204fe6c69267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Exports'])[8]/following::a[3]</value>
      <webElementGuid>6936eca4-93be-40df-86ad-3352811970ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[12]/preceding::a[1]</value>
      <webElementGuid>1a8343d1-f967-4079-994f-4767947c1fa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[12]/preceding::a[1]</value>
      <webElementGuid>cdc9d7c0-85f6-480f-bbc9-2de429ce02c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/p/a</value>
      <webElementGuid>ed3f798e-0867-4f2a-829b-d150fa7d7031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Create New' or . = 'Create New')]</value>
      <webElementGuid>417f235c-6ff4-40b0-b087-ae4b92edec0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
