<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Export Type_btn btn-sm btn-primary e_73c9c6</name>
   <tag></tag>
   <elementGuidId>d8c71ca7-70a4-40ff-932e-eff6ad5da900</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-sm.btn-primary.edit-rule-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='be186d09-5042-4120-b09d-3e6cd7b8a097']/tr/td/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Edit Delete 2 Vendor test 4237 10 JUST_DELAYED&quot;i] >> internal:role=button >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eee61aa2-404f-4351-a8a6-fbcabb7bf358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-primary edit-rule-btn</value>
      <webElementGuid>5f76e9e1-80d8-4c1c-a016-9bb8a267f362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-soptype</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>6ee5499f-0adf-4982-bf83-0ea394e67533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>312</value>
      <webElementGuid>7745ac77-1c55-41e6-bd90-f48d127117cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-prophet21id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8356af07-344c-442d-8345-bc6c2b9b92c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>78d23d4d-e94a-43d4-84b6-3362bba33449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;be186d09-5042-4120-b09d-3e6cd7b8a097&quot;)/tr[@class=&quot;k-table-row k-master-row&quot;]/td[@class=&quot;k-table-td&quot;]/button[@class=&quot;btn btn-sm btn-primary edit-rule-btn&quot;]</value>
      <webElementGuid>c934e525-2896-440f-a2a3-649fc2f48203</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='be186d09-5042-4120-b09d-3e6cd7b8a097']/tr/td/button</value>
      <webElementGuid>5fbcd21d-3327-4746-b5a6-8df595c9261d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export Type'])[1]/following::button[1]</value>
      <webElementGuid>b7d43743-46f8-4fc6-b2d9-4777812bf535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Result When False'])[1]/following::button[1]</value>
      <webElementGuid>387b5e0d-1bb8-43af-a561-c50d6aa9aa98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[2]/preceding::button[1]</value>
      <webElementGuid>8b769985-7bb0-449e-9bcb-a89f545a5bd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor'])[1]/preceding::button[2]</value>
      <webElementGuid>f0949de6-0dd1-4a64-b971-2be02d1c95bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/button</value>
      <webElementGuid>712a81d3-1975-4e78-9bfd-1f6d2a5cf7b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>b61ea5c1-9d07-46b2-9fcf-6eb5346ebfe9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
