<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Result When False_ResultWhenFalse</name>
   <tag></tag>
   <elementGuidId>74c5750d-03ed-409a-9af6-a2bb61360aa4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ResultWhenFalse</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ResultWhenFalse']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Result When False&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e35c6c69-ccd4-45f2-9517-85cfb14e7acc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d4ebc343-8398-4b5d-af5b-a68b9c4959ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ResultWhenFalse</value>
      <webElementGuid>60a6e363-4201-4bd7-bb52-227ac1b4be75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ResultWhenFalse</value>
      <webElementGuid>1457c88b-984a-44c5-b231-2af079c1e31f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8d53fdab-764d-4101-a94a-46eaddabf08e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ResultWhenFalse&quot;)</value>
      <webElementGuid>080b2958-8fbe-4da5-8e3a-71fdcccab4ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ResultWhenFalse']</value>
      <webElementGuid>90a02626-31a7-4c2e-8e9b-5d4c3283d14e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customerRuleForm']/div[2]/div[4]/div[2]/input</value>
      <webElementGuid>bdf5a5ac-8797-4852-adf1-406ae08f43ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>542f3f77-b0fe-4240-a733-58a6a3cfde2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ResultWhenFalse' and @name = 'ResultWhenFalse' and @type = 'text']</value>
      <webElementGuid>8cda385a-db2e-40e2-b3e7-aebcffb35b48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
