<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label</name>
   <tag></tag>
   <elementGuidId>01c8f62c-5b14-4b89-892a-3d0e0b0d29d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='customerRuleForm']/div[2]/div[4]/div[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#customerRuleForm >> internal:text=&quot;Result When False&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>947e02cf-c3e9-4bf4-8151-d1d2c4bda7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ResultWhenFalse</value>
      <webElementGuid>30606506-fd61-4426-9d41-08a5ebb23cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Result When False</value>
      <webElementGuid>1288921e-0d63-4c22-b816-f0ad106ba64f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customerRuleForm&quot;)/div[@class=&quot;modal-body&quot;]/div[@class=&quot;row mt-2&quot;]/div[@class=&quot;col-md-6 form-group&quot;]/label[1]</value>
      <webElementGuid>feebefd9-eee1-4353-a759-6a810c2798f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customerRuleForm']/div[2]/div[4]/div[2]/label</value>
      <webElementGuid>1e711d81-bf65-4699-bc49-b48ae1f3343b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::label[1]</value>
      <webElementGuid>ee842480-4dfc-46fa-ae1d-10b6697a233c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Result When True'])[3]/following::label[1]</value>
      <webElementGuid>540356fa-d9ee-4b0f-8834-d14866917307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Off'])[1]/preceding::label[1]</value>
      <webElementGuid>3c5a71c9-0b5a-432b-ab4c-d80c163f6644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Evaluate True Result'])[1]/preceding::label[1]</value>
      <webElementGuid>2a7a9699-0d3e-4f60-ab2a-e05bf7720c84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/label</value>
      <webElementGuid>173bbe26-3466-41f9-84dd-a62e2fbcde37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Result When False' or . = 'Result When False')]</value>
      <webElementGuid>55fe723a-7c28-4c55-9d24-37703b2074d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
