<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__EvaluationTypeId</name>
   <tag></tag>
   <elementGuidId>e57449a6-a67e-498f-ab96-4e331f92f0a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EvaluationTypeId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='EvaluationTypeId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Evaluation Type&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bc172952-3ece-4011-a604-69e60c999321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>ef387a7f-7c09-485c-8fcd-0c1c9d5cd247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b6a86417-22aa-492c-99c3-e7f0240712f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Evaluation Type field is required.</value>
      <webElementGuid>a7bfc08a-6879-42ff-9687-11878e197976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EvaluationTypeId</value>
      <webElementGuid>0d004900-4309-4b73-9724-d1c1cbc4b8b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EvaluationTypeId</value>
      <webElementGuid>6d1a7954-dfa2-4db0-b971-37c3f2b1811c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>0f65951d-532e-43d8-8c7e-9c79de9fcc49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select evaluation type...
Header - 1
Line - 2
</value>
      <webElementGuid>ece87809-f902-49d6-aebf-03a7d516b41f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EvaluationTypeId&quot;)</value>
      <webElementGuid>74d0c292-4ae7-4a15-826c-9ef7a80045e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='EvaluationTypeId']</value>
      <webElementGuid>9d4d4119-4490-4fd6-aef6-61ea117c6b36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customerRuleForm']/div[2]/div[2]/div/select</value>
      <webElementGuid>5d5eefc6-dae1-4a66-8989-c4fbbfa4572f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::select[1]</value>
      <webElementGuid>277c9c13-32bd-417a-bd08-b9e899c8cec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Evaluation Type'])[3]/following::select[1]</value>
      <webElementGuid>d4fa1a38-7a6b-4fe1-82cf-fa75bc29b9c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export Type'])[3]/preceding::select[1]</value>
      <webElementGuid>64aeb5fe-e0c5-4d81-8d10-20639a961e4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::select[1]</value>
      <webElementGuid>35032caa-20e2-4b7d-acb0-950f1294b907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>f6135932-1475-4fcd-a85a-6bc4b816a2d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'EvaluationTypeId' and @name = 'EvaluationTypeId' and (text() = 'Select evaluation type...
Header - 1
Line - 2
' or . = 'Select evaluation type...
Header - 1
Line - 2
')]</value>
      <webElementGuid>3b06040d-34bd-4e53-9498-ae0e64763ee9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
