<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__k-input-value-text_1</name>
   <tag></tag>
   <elementGuidId>e8746269-73d0-4d30-840b-013647ab2750</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b1aa9638-0b6f-4a9b-a761-671f2ca13dfb > span.k-input-value-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='b1aa9638-0b6f-4a9b-a761-671f2ca13dfb']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#customerRuleForm >> internal:text=&quot;JUST_DELAYED&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0a381359-25b6-4b67-8084-7e982ac6f8a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input-value-text</value>
      <webElementGuid>f203ab42-c555-41dc-aa10-2b0d3e4925ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JUST_DELAYED</value>
      <webElementGuid>4b2bbb15-567a-4d2b-8146-3f20c0c61dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1aa9638-0b6f-4a9b-a761-671f2ca13dfb&quot;)/span[@class=&quot;k-input-value-text&quot;]</value>
      <webElementGuid>eeab4d3e-c984-459b-bcff-7617c105811e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='b1aa9638-0b6f-4a9b-a761-671f2ca13dfb']/span</value>
      <webElementGuid>d1372cbe-f272-4f15-b397-328ba3d54e93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::span[3]</value>
      <webElementGuid>c8a3e06e-61b5-4162-8457-04329ef159f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export Type'])[3]/following::span[4]</value>
      <webElementGuid>1fef9b51-b53c-4d57-a2e5-5eb6a2ab2a71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Property Name'])[3]/preceding::span[4]</value>
      <webElementGuid>6d32678b-b0c4-4a27-b2b5-699017f9139f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::span[4]</value>
      <webElementGuid>2543628d-8c15-4014-aad6-c9c7037082b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/span</value>
      <webElementGuid>ca7ac50a-aab8-474d-a339-39d5a514871b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'JUST_DELAYED' or . = 'JUST_DELAYED')]</value>
      <webElementGuid>b0b029a9-b3f7-4f83-98a3-707b8e3abd08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
