<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Off_k-switch-thumb k-rounded-full</name>
   <tag></tag>
   <elementGuidId>aa3803e4-bbbe-46b9-a70e-abed9668e94b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.k-switch-thumb.k-rounded-full</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='customerRuleForm']/div[2]/div[5]/div/span/span[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=switch[name=&quot;Evaluate True Result&quot;i] >> span >> nth=4</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>99f51bb8-fa32-4950-9119-6eb5cce8bc85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-switch-thumb k-rounded-full</value>
      <webElementGuid>49a11892-db04-4bce-bae1-28e6b40ee594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customerRuleForm&quot;)/div[@class=&quot;modal-body&quot;]/div[@class=&quot;row mt-3&quot;]/div[@class=&quot;col-md-6 form-check d-flex align-items-center gap-2&quot;]/span[@class=&quot;k-switch k-switch-md k-rounded-full k-switch-off&quot;]/span[@class=&quot;k-switch-thumb-wrap&quot;]/span[@class=&quot;k-switch-thumb k-rounded-full&quot;]</value>
      <webElementGuid>29f7504f-6579-47f2-a985-b800b4aaa073</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customerRuleForm']/div[2]/div[5]/div/span/span[2]/span</value>
      <webElementGuid>4e20257b-6f49-4231-ab66-974c9ed83555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/span/span[2]/span</value>
      <webElementGuid>9cb09ab8-d0fb-4a6f-aefe-ab39bb033422</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
