<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Edit</name>
   <tag></tag>
   <elementGuidId>79ec8cfa-f695-47d8-bda1-5781c49652da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='f61aa805-0ef4-485d-aa0b-d48f11e5a197']/tr[11]/td/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6996a465-1a56-4fb4-8849-55688cf789a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>81b81563-1a76-4b5a-a734-a3b75c686b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Export/ExportCustomer/Edit/123</value>
      <webElementGuid>d7a23ebc-e9c6-47cc-b4d5-0246cc8d5842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>e55660e7-33fe-48e5-8232-09fdc4dc9190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f61aa805-0ef4-485d-aa0b-d48f11e5a197&quot;)/tr[@class=&quot;k-table-row k-master-row&quot;]/td[@class=&quot;k-table-td&quot;]/a[@class=&quot;btn btn-primary&quot;]</value>
      <webElementGuid>5efe669c-90c4-4e78-b01a-c4abc2241e82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='f61aa805-0ef4-485d-aa0b-d48f11e5a197']/tr[11]/td/a</value>
      <webElementGuid>d4264acc-d571-426e-82a9-ce41e19e652c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Edit')])[11]</value>
      <webElementGuid>de57815a-1d47-4902-9d6f-a3428fba828e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='false'])[47]/following::a[1]</value>
      <webElementGuid>fcebc31a-2913-4ffc-b430-57fe95cf4e8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='false'])[46]/following::a[1]</value>
      <webElementGuid>f1c05b74-d856-47d3-bf2b-6e401c8fa5fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CSV, XML, PDF, Excel'])[1]/preceding::a[1]</value>
      <webElementGuid>76d8bf1d-c9f5-4dd7-8578-42addbdb7ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='true'])[53]/preceding::a[1]</value>
      <webElementGuid>1f5e7ad8-e5bc-4f3d-af98-2c2f8012e307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Export/ExportCustomer/Edit/123')]</value>
      <webElementGuid>9ec127ce-74c9-40d3-8659-92dc2707253c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[11]/td/a</value>
      <webElementGuid>ad80ec31-4e46-45bb-bb4f-a0363c3cebc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Export/ExportCustomer/Edit/123' and (text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>d03e7b30-88ec-4c0b-9e76-3db16ae6490e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
