<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Delay Amount_DelayAmount</name>
   <tag></tag>
   <elementGuidId>e53ed980-92d1-4d64-872a-4a657ca54e11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DelayAmount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DelayAmount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2c935619-586e-4738-9329-89e92daff66a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>b800f9b5-e2ec-4132-baa5-719efb379a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6bdf6eb4-38ec-49fd-936a-0f1d38540e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4b7bfe9c-fce6-4238-a747-d9b95023ea7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value = this.value.replace(/[^0-9]/g,'');</value>
      <webElementGuid>e516d853-1676-449c-bfa9-4418cc1afc0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6e79adfd-7160-4aef-91cd-6c15d49b8b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DelayAmount</value>
      <webElementGuid>b30e38d1-f040-4b49-a971-92e37f21f8a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DelayAmount</value>
      <webElementGuid>799370cb-12a8-4722-8472-c3d556b15f50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DelayAmount&quot;)</value>
      <webElementGuid>0ec063d3-a1c1-4217-a912-f2e23c031142</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DelayAmount']</value>
      <webElementGuid>ff2537ea-9719-4f97-9cf7-6e0324600190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='CreateExportCustomerForm']/div/div[5]/input</value>
      <webElementGuid>66c8aac0-0b03-435e-b3b4-bf180da7693f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>6e23fce4-b3f9-45c3-b602-1f863254a271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'DelayAmount' and @name = 'DelayAmount']</value>
      <webElementGuid>301c5dcb-efeb-4a89-a02a-6e11aa61ed89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
