<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NISC COMP ID_NISC_COMP_ID</name>
   <tag></tag>
   <elementGuidId>c6900dd3-8e60-46db-9dd5-299ac01912ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NISC_COMP_ID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NISC_COMP_ID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef95ba09-93b6-4f5c-ad59-3e19c0f3eff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>45123b99-6a21-4719-94a5-579a59127c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>82f20160-ea60-4bb9-bcc7-5567e830f3b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ee98dc2d-3347-4f61-a535-97f03d1ef18d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f4de408c-ca8c-427b-9b1a-350e7e978721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NISC_COMP_ID</value>
      <webElementGuid>22d52211-2868-4f2b-b9af-30c56f4926ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NISC_COMP_ID</value>
      <webElementGuid>007ef078-5e23-4bee-86f2-07f92cad8049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NISC_COMP_ID&quot;)</value>
      <webElementGuid>74401f5d-7227-47bb-a174-0ead6d3a79a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NISC_COMP_ID']</value>
      <webElementGuid>5bee3521-4947-4059-a343-8dbdf0d9a324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='CreateExportCustomerForm']/div/div[27]/input</value>
      <webElementGuid>76dd458a-12cc-49df-9fdf-00b8610284c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[27]/input</value>
      <webElementGuid>7b90f76d-8aa1-445e-9b1d-61ee82390a7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'NISC_COMP_ID' and @name = 'NISC_COMP_ID']</value>
      <webElementGuid>0d679b7a-1261-4008-bcb0-8713fd158215</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
