<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_External Endpoint_ExternalEndPoint</name>
   <tag></tag>
   <elementGuidId>90df4fa3-6b12-44ae-a22b-1039a31e10e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ExternalEndPoint</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ExternalEndPoint']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49df83e4-162d-466d-aece-579e1926712c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fe4faf24-95ab-4d0c-9995-bcabb856cabe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>919f7580-05e7-4137-a995-0d518a6a25c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d1d1e889-863f-4777-89d9-eb8d809a4881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field External Endpoint must be a string with a maximum length of 200.</value>
      <webElementGuid>63a9aeec-0bf3-4b4f-a850-0059a3c5cecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>ac0b7f6f-0769-4dcd-8fdf-27202687fdb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ExternalEndPoint</value>
      <webElementGuid>87aed593-a226-42eb-81b6-000a91ceb708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>7d638a7b-c109-4163-9fac-c0fedf063b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ExternalEndPoint</value>
      <webElementGuid>b1e28337-0dfd-4ca4-9411-bfad97dbfc8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ExternalEndPoint&quot;)</value>
      <webElementGuid>56226338-9c2e-49b2-9fc2-dffd7067e7d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ExternalEndPoint']</value>
      <webElementGuid>bb38c07e-d771-4614-bc1a-da01813eed9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='CreateExportCustomerForm']/div/div[12]/input</value>
      <webElementGuid>5d949968-a1bb-40a4-8469-076f3ec32e1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/input</value>
      <webElementGuid>1f0b2f0e-2d7a-4bd1-83c2-ba1ac2e75897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ExternalEndPoint' and @name = 'ExternalEndPoint']</value>
      <webElementGuid>7b0bf9d1-d1c1-4aed-afc9-2b6f8c17d2f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
