<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_External Password_ExternalPassword</name>
   <tag></tag>
   <elementGuidId>fbe70017-972e-4459-b497-12488690a984</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ExternalPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ExternalPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b73dab8-89ae-4366-a5d8-ea1ff375307d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>26353c6c-ff27-4cf1-a0cd-cf7e9dca254c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control pe-5</value>
      <webElementGuid>3d8c400b-324c-486d-a9a5-4cb7acfb85f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ExternalPassword</value>
      <webElementGuid>0fb9e1e1-b468-423f-af28-15fe272af768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ExternalPassword</value>
      <webElementGuid>1f27d288-676f-4ef4-80d2-3a4ae834d2d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ExternalPassword&quot;)</value>
      <webElementGuid>72256924-6e7d-4b62-ab21-e0db36d18a4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ExternalPassword']</value>
      <webElementGuid>6c92901d-74af-4176-bcb4-9e3c70a11f32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='CreateExportCustomerForm']/div/div[11]/div/input</value>
      <webElementGuid>16398da5-fad0-4149-b800-907581e29802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/input</value>
      <webElementGuid>fbcbcb1b-2b2a-4ff1-afe4-bb2177962784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'ExternalPassword' and @name = 'ExternalPassword']</value>
      <webElementGuid>af923464-2725-492d-b43a-33d17ac78a22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
