<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Prophet21ID</name>
   <tag></tag>
   <elementGuidId>f23aa796-9da6-4d2d-8ba7-2cf3b5716ae9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Prophet21ID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Prophet21ID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b35441f-82af-4330-9b49-e2c26b89b533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>11e5fa2a-4e36-48fb-a423-0d720d7c5fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d4a79afa-f2c4-4592-a0de-73943c885cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b909892f-f131-46b6-93bf-58989d684e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value = this.value.replace(/[^0-9]/g,'');</value>
      <webElementGuid>78f971e3-a90d-4f65-8edf-49f0c8fb3751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cf69ccc3-5eec-4492-8ab0-7607b9c66455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>61f20206-5661-46fa-bdb8-0a1f49211cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Prophet21 ID field is required.</value>
      <webElementGuid>7a6be32f-8cdd-434c-a2ad-943ccc76f342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Prophet21ID</value>
      <webElementGuid>bf9d58a5-c47e-4f6e-afdb-513f3821c08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Prophet21ID</value>
      <webElementGuid>9b28b8b1-bdaa-4791-bec4-d5e01335e8d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Prophet21ID&quot;)</value>
      <webElementGuid>06f1669c-d631-40fc-b70c-78cccb5d9f4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Prophet21ID']</value>
      <webElementGuid>92d2bbc7-a8d8-4101-b37e-d96bb82791b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='CreateExportCustomerForm']/div/div/input</value>
      <webElementGuid>bdb52a59-6c34-418d-8586-448915c79362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>2dcb817a-9a2b-43dd-a4d3-4fcedfa9b9c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'Prophet21ID' and @name = 'Prophet21ID']</value>
      <webElementGuid>cd74f3de-5fd0-4bb5-8fb7-4b92ba6958f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
