<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PO Export Customer ID_POExportCustomerID</name>
   <tag></tag>
   <elementGuidId>06054d0e-53c1-4274-beb8-6637567633a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#POExportCustomerID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='POExportCustomerID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5f09a0b-6750-479b-8598-4f1abe5fff87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>03d6c3fb-88b8-46ea-8efa-cb743248f1e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2858239d-cbd7-4b7d-bdfd-92ea124c5aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a3c5a011-92ec-42c8-95b3-cc9067e4a130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>749aa154-3010-40ba-ad8b-d2e6efb2ffad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>POExportCustomerID</value>
      <webElementGuid>00c3387c-811b-42e2-a267-73d237f17665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>POExportCustomerID</value>
      <webElementGuid>c172cd6c-3243-4298-8368-7d3ed28c0d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;POExportCustomerID&quot;)</value>
      <webElementGuid>d7559636-08cd-40ac-9469-50f652bbc1bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='POExportCustomerID']</value>
      <webElementGuid>c8f38ff6-700a-436e-ba23-dad6dd755a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='CreateExportCustomerForm']/div/div[29]/input</value>
      <webElementGuid>2090cdc0-a69b-4a18-9432-99ff1299c149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[29]/input</value>
      <webElementGuid>fecc8e38-7207-43b4-a53f-6f6e042218ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'POExportCustomerID' and @name = 'POExportCustomerID']</value>
      <webElementGuid>6d90b869-f701-4113-9def-0f8a5228920e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
