<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TEC Process Emails_TECProcessEmails</name>
   <tag></tag>
   <elementGuidId>d8da511b-5e1c-4821-91b7-917b61d69ec1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TECProcessEmails</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TECProcessEmails']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f381969-115f-47ad-8188-839f313ed426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>11305005-8ed1-48e9-a3be-c8e845efefd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a5d925cc-4f21-4f0f-aed8-c9b284581a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7bf419c8-de6c-412a-bcdf-245fd5418487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field TEC Process Emails must be a string with a maximum length of 200.</value>
      <webElementGuid>4c24a367-4f70-416c-9511-2fbeb6488583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>a965db19-ebc3-4bff-97a4-55f730ebcada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TECProcessEmails</value>
      <webElementGuid>d360cb20-c4cb-4922-a753-0cc040ce3adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>8a4e219f-2343-40b1-ba54-7888c5d950d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TECProcessEmails</value>
      <webElementGuid>49ebdd83-f7d3-4159-8c5e-80ed8d64610f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TECProcessEmails&quot;)</value>
      <webElementGuid>5166b8d1-f6c1-41d1-adf0-c9c423e9a146</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TECProcessEmails']</value>
      <webElementGuid>a4585349-80cc-4fe0-b4ff-75dee3108347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='CreateExportCustomerForm']/div/div[15]/input</value>
      <webElementGuid>44476ad6-b883-476a-bcb7-7ad5b10aab1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/input</value>
      <webElementGuid>e22e76c9-8d04-48a9-9ec7-323a6ddca778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'TECProcessEmails' and @name = 'TECProcessEmails']</value>
      <webElementGuid>9d946834-7a5f-4642-8639-9407572324b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
