<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Uses Delay_UsesDelay</name>
   <tag></tag>
   <elementGuidId>84424d11-7693-4dfd-9006-56182ee4c1f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UsesDelay</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UsesDelay']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49f0bc6b-0cc8-41eb-b744-d37c9f8a0501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c5f940e3-42e0-424e-a806-3e89379ac93f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4fc14bb7-660d-4f66-a42a-5a327819a0ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2339eb89-4ba5-439d-a500-2b915fce8802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value = this.value.replace(/[^0-9]/g,'');</value>
      <webElementGuid>63761cb5-0fcf-49be-ba93-89393c81bb99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3486bef5-34f5-40a0-b27e-9be7f8a3c03c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UsesDelay</value>
      <webElementGuid>193dd0e2-4066-4fa5-a3d5-76cd2854ecd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UsesDelay</value>
      <webElementGuid>2ca926d8-aed6-4a56-9e33-d3e4e55b4ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UsesDelay&quot;)</value>
      <webElementGuid>f0e558b5-dd27-4c7a-be15-d47cebde96ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UsesDelay']</value>
      <webElementGuid>5f270f52-29a3-4d55-a776-c8a9891a1e27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='CreateExportCustomerForm']/div/div[4]/input</value>
      <webElementGuid>022f9849-fbdf-4bf8-8ebd-983dbd5d7272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>bd13bb4c-a8b4-4b52-9c89-3a23294a09ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'UsesDelay' and @name = 'UsesDelay']</value>
      <webElementGuid>d5e5e7d3-e37a-48ef-b617-f5efdd5e52ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
