<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_QR Code String_QRCodeString</name>
   <tag></tag>
   <elementGuidId>184f4336-a67d-4b8c-8acf-30a119373061</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#QRCodeString</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='QRCodeString']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c66a749c-d6b6-48f1-82ca-1afdd830f472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bb2344a8-6170-4605-8860-e68f992f11d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d03744d5-b785-4582-844b-c12102f7a5c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>583ed9a6-5e0f-4564-9e16-3781fe908dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field QR Code String must be a string with a maximum length of 50.</value>
      <webElementGuid>67231d3f-7cb2-4fa9-9f9a-48a84a40cd81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>79c8f8cd-b6e6-4dd0-b49c-74a7ed0eae29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>QRCodeString</value>
      <webElementGuid>9bc43449-4d85-46d2-bd3f-c4b8bff399b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>01780370-4904-4af6-849a-50776676c504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>QRCodeString</value>
      <webElementGuid>48264727-2e0d-4190-a990-f21d79a992ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QRCodeString&quot;)</value>
      <webElementGuid>a6bf5694-ff56-40e6-bc15-7fa57f5d2274</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='QRCodeString']</value>
      <webElementGuid>8eae52c2-7cc7-4c4d-98cc-12ee867d0edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='CreateExportCustomerForm']/div/div[22]/input</value>
      <webElementGuid>0f93d119-a2e0-45de-be87-f08a0a125177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/input</value>
      <webElementGuid>8e89f603-6cf7-401d-a602-62b0a895a0f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'QRCodeString' and @name = 'QRCodeString']</value>
      <webElementGuid>0b4f62c5-b198-43dc-a457-18112260d02f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
