<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__NotificationEmails</name>
   <tag></tag>
   <elementGuidId>e8e58516-faaf-4a3d-91b9-821163ae7e13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NotificationEmails</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NotificationEmails']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>81ebaed2-d855-470a-b1bf-ff7fa235f06c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>375999f6-379b-41d4-b57d-f7e7853a5f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>3b75a139-e2d8-45ce-9754-b73d6dd9c307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>11b16b92-bf75-4ec5-8198-8b1018245e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-email</name>
      <type>Main</type>
      <value>Enter a valid email address.</value>
      <webElementGuid>d86fb739-1d88-4924-b982-5c28c97fb613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Notification Emails must be a string with a maximum length of 500.</value>
      <webElementGuid>d5d4443f-8d4a-4e59-b3c4-d55b9f341bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>5a0dc477-4dbc-42c1-b025-511f988546c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Notification Emails are required.</value>
      <webElementGuid>65eea9c3-eef4-46c4-8a18-17d9f68c0408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NotificationEmails</value>
      <webElementGuid>bbc94fad-180b-48d3-9121-75aaf60bbde6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>badbb753-0269-4d97-9817-03c32f51e2a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NotificationEmails</value>
      <webElementGuid>718fd612-1777-4f3d-bc3c-53f6dcfeb5a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NotificationEmails&quot;)</value>
      <webElementGuid>7395a7c4-6410-497c-989f-624a81e914da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NotificationEmails']</value>
      <webElementGuid>1d12ac2a-7a6a-4cda-9da2-4ff4ee5a0b2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='CreateExportCustomerForm']/div/div[9]/input</value>
      <webElementGuid>f5307b00-b5ec-448e-918f-0adfd8683ad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/input</value>
      <webElementGuid>4dc71773-b762-4902-b9af-aab0791a7f4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'NotificationEmails' and @name = 'NotificationEmails']</value>
      <webElementGuid>4a0722de-5a36-4bba-bbbf-f5a6442ef3dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
