<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SEDC DB Name_SEDCDatabaseName</name>
   <tag></tag>
   <elementGuidId>6303eaf8-0636-4fcc-b256-c8ceb443cd34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SEDCDatabaseName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SEDCDatabaseName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f45b79a4-68b3-4789-98f2-c4e538283c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>aa6d65b1-2c1f-49fb-8c0d-ec2f5cbec1d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>91b9d6f4-ef8f-4300-b4c0-b5e09b617ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eeb4d70b-d691-48b6-9ec6-3f0f87232f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field SEDC DB Name must be a string with a maximum length of 200.</value>
      <webElementGuid>184a321d-5153-4595-84ac-20f04db999a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>d8fd6691-d83e-4a54-a777-ef4cc0ca0609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SEDCDatabaseName</value>
      <webElementGuid>4342a5c4-4917-4504-8955-c04bbb7939fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>17804cdd-36d5-4938-a93f-8b59ade5fc38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SEDCDatabaseName</value>
      <webElementGuid>9790b51b-ce35-42aa-b08e-dc69e08cf969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SEDCDatabaseName&quot;)</value>
      <webElementGuid>6a3ca5e1-2a2a-496d-b9bd-17eb44acf4a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SEDCDatabaseName']</value>
      <webElementGuid>9d4e6b35-5c0e-4cbf-8b94-86e76fbd48d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='CreateExportCustomerForm']/div/div[13]/input</value>
      <webElementGuid>c7b561ac-5600-4e24-8bf8-dc144e64b43e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/input</value>
      <webElementGuid>6a0f52b5-47c4-4493-9f52-79d4cfa27449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'SEDCDatabaseName' and @name = 'SEDCDatabaseName']</value>
      <webElementGuid>91d697b4-6ab5-4e70-bdd9-1697013f98eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
