<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_PDF</name>
   <tag></tag>
   <elementGuidId>dfc4fbc4-2cff-483f-b2a1-1a8b738d3765</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.k-list-item.k-hover > span.k-list-item-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ExportTypesList_listbox']/li[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>665fbcb7-ce0a-4d2b-8af2-98f92ae611c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-list-item-text</value>
      <webElementGuid>e7ab3f7c-266a-4a72-9136-58019288217a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PDF</value>
      <webElementGuid>df85587a-8348-47c1-be00-aafb4ee22b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ExportTypesList_listbox&quot;)/li[@class=&quot;k-list-item k-hover&quot;]/span[@class=&quot;k-list-item-text&quot;]</value>
      <webElementGuid>78c6465f-e5ae-443a-82ba-f98948172356</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ExportTypesList_listbox']/li[3]/span</value>
      <webElementGuid>e0f20dc8-8a8c-49ac-85d9-e33e9150b909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XML'])[2]/following::span[1]</value>
      <webElementGuid>51662618-41b2-4810-9df3-1add50afaf0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CSV'])[3]/following::span[2]</value>
      <webElementGuid>396c620d-0e41-4112-800f-39e0f853ffba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Excel'])[2]/preceding::span[1]</value>
      <webElementGuid>aea745ad-3954-4f3a-bdb9-ca35d09f771c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data found.'])[1]/preceding::span[2]</value>
      <webElementGuid>0287020b-8bd4-4b89-835c-01ab95b1b30e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[3]/span</value>
      <webElementGuid>8bcce6be-ce04-4df6-8edd-9ab31af7d07d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'PDF' or . = 'PDF')]</value>
      <webElementGuid>6a48dcab-3c00-421c-ab07-f66797a69350</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
