<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_CSV</name>
   <tag></tag>
   <elementGuidId>3a9e64bf-d9fa-48b5-9e23-e78648b4dd73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.k-list-item-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='d6c01721-1aa5-4741-be38-d185f192a11a']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6a5b9b96-9e03-4fd0-8389-b3ccc94ad1dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-list-item-text</value>
      <webElementGuid>5287d38b-b6e6-4249-abc1-ff969d3e282e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CSV</value>
      <webElementGuid>eca2d9e9-c1c4-4af9-b997-f3f0c8b29d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d6c01721-1aa5-4741-be38-d185f192a11a&quot;)/span[@class=&quot;k-list-item-text&quot;]</value>
      <webElementGuid>3b9ddf06-a790-49af-a6c7-7f03e97cb15a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='d6c01721-1aa5-4741-be38-d185f192a11a']/span</value>
      <webElementGuid>4250784f-b1ab-4ad4-8d4d-51676149b067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto Updates'])[1]/following::span[5]</value>
      <webElementGuid>70c8825e-d798-4d6b-98fd-bc7fee889f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save Histry'])[1]/following::span[8]</value>
      <webElementGuid>842d0594-db38-4147-b0a9-7086c11b03f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XML'])[2]/preceding::span[1]</value>
      <webElementGuid>a8c989b0-a953-4e2e-921a-17ad19bf8ca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PDF'])[2]/preceding::span[2]</value>
      <webElementGuid>c60ee0a7-391f-4171-a6ac-2e31b4653761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/span</value>
      <webElementGuid>16fbf0ef-f3e3-434d-872a-54235f49848b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'CSV' or . = 'CSV')]</value>
      <webElementGuid>d169b051-8e40-4c1c-b6ee-9452bfc5d48d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
