<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Export Specific Notification_Expor_c4e8e8</name>
   <tag></tag>
   <elementGuidId>efb58997-3e41-4649-bf98-fc30572c7c7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ExportSpecificNotification</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ExportSpecificNotification']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>697cf8e9-a571-42cf-853a-48dddf46ab54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6717a68d-f2e7-4624-98ae-35070465e639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>d3c52240-90ac-4ebd-9178-79f1a9bf96ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ExportSpecificNotification</value>
      <webElementGuid>b62f51a4-6291-4f74-9cf9-3d9fd322be40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ExportSpecificNotification</value>
      <webElementGuid>9aba3bd0-4060-4e43-a115-6937937e797f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ExportSpecificNotification&quot;)</value>
      <webElementGuid>70949003-5d46-4ced-9362-654ebf76af7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ExportSpecificNotification']</value>
      <webElementGuid>476b1a40-a75f-439c-bcad-4849a8e93702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='CreateExportCustomerForm']/div/div[30]/textarea</value>
      <webElementGuid>a92eb5d4-e30c-442c-88c8-2047dd5635c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>6259e4ad-5456-4872-9268-30725df04816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'ExportSpecificNotification' and @name = 'ExportSpecificNotification']</value>
      <webElementGuid>e1843b3a-abb0-4336-ba88-2d27b05c60ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
