<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__k-input-value-text</name>
   <tag></tag>
   <elementGuidId>55d041db-fc3f-48a7-8203-1a2f8a8f66f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.k-input-value-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ebf6e6f0-c181-4d0f-a524-6d07eb9ea26f']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#CreateExportCustomerForm >> internal:text=&quot;Select delayed export type...&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b785d4b6-4e73-49d1-bcf0-2d6c9cbf6ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input-value-text</value>
      <webElementGuid>5a34c310-7e1e-4359-a2d8-276ed309c284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select delayed export type...</value>
      <webElementGuid>a334617e-47a6-4c8a-9491-074e66dc57ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ebf6e6f0-c181-4d0f-a524-6d07eb9ea26f&quot;)/span[@class=&quot;k-input-value-text&quot;]</value>
      <webElementGuid>287457fc-0468-433c-a64a-0ad02092e2c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='ebf6e6f0-c181-4d0f-a524-6d07eb9ea26f']/span</value>
      <webElementGuid>6a13c172-0c50-43a5-950c-5fd35e75ed7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::span[3]</value>
      <webElementGuid>78543e1f-804e-4b7c-8172-bd1801718a5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delayed Export Type'])[1]/following::span[4]</value>
      <webElementGuid>9d4ca8f2-c88e-4a24-81b5-9766cb8f1d4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send Export Notification Email'])[1]/preceding::span[4]</value>
      <webElementGuid>a44b8664-3898-42d1-9278-271ef85db8d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO'])[1]/preceding::span[5]</value>
      <webElementGuid>cee76c82-83e7-4198-81f4-f0d844125f32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select delayed export type...']/parent::*</value>
      <webElementGuid>02d432fb-a4f3-4637-b233-89aab21d7366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/span[2]/span/span</value>
      <webElementGuid>43987e34-91a8-4153-b479-6709795d8819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Select delayed export type...' or . = 'Select delayed export type...')]</value>
      <webElementGuid>d3a07e75-cef9-4bf4-b8ec-cfdea68b5d18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
