<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>excel_delayexport</description>
   <name>excel_delayexport</name>
   <tag></tag>
   <elementGuidId>4393840f-d76c-4a61-9146-708e9f9ef411</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@class='k-input-value-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
