<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NISC Barcode User_NISC_BARCODE_USER</name>
   <tag></tag>
   <elementGuidId>b2cc20a6-5ada-4538-8ad7-2ba55c6a8129</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NISC_BARCODE_USER</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NISC_BARCODE_USER']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d925fb84-5711-422c-959c-e9c09ce21097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1b367a2b-7c8c-46d1-9386-969b9087d3da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>be562c9d-1da6-467d-b4fa-1fd0660fe06e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>56534c7b-8c41-4ef7-a49a-bd4b7bfb2c5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field NISC Barcode User must be a string with a maximum length of 50.</value>
      <webElementGuid>4a9ab7f5-1404-4f78-8941-dbb31d76e86c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>0e39cbe2-cf5c-4b3a-b280-d505b0a9f9be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NISC_BARCODE_USER</value>
      <webElementGuid>29b4409a-b982-4dcc-8f3e-8c7c8965d196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>1fe607d5-f406-487c-8215-f66640b67b5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NISC_BARCODE_USER</value>
      <webElementGuid>7c9cde97-654e-49f3-b085-22f4ae6cecff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NISC_BARCODE_USER&quot;)</value>
      <webElementGuid>2f835b58-76ca-4097-9a56-ec476f203753</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NISC_BARCODE_USER']</value>
      <webElementGuid>946afad7-e097-48f4-97c9-19aa24e935d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='CreateExportCustomerForm']/div/div[28]/input</value>
      <webElementGuid>c2c9549e-938b-445a-9900-4980d71c25c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[28]/input</value>
      <webElementGuid>226331e4-e828-4ac1-8c55-d663a6dee3b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'NISC_BARCODE_USER' and @name = 'NISC_BARCODE_USER']</value>
      <webElementGuid>49ec1703-d6f8-4c35-818b-3a9f4266e921</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
