<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_External Username_ExternalUserName</name>
   <tag></tag>
   <elementGuidId>a9ba58ab-00d8-4932-b0d1-3001e75aec4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ExternalUserName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ExternalUserName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f710d2cb-1a83-4bc4-b94e-42b1bf2f7a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f8d4c88a-6eb3-428e-9dbf-68ceb265d7b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f2706fbc-0120-4c3a-9745-43b061297062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>557f1605-e58d-487e-94c3-ec552e291026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field External Username must be a string with a maximum length of 50.</value>
      <webElementGuid>bbe5a46b-6fbb-4cf1-a70c-bd2d37c6db02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>8223060e-9bd6-435c-9655-2068439a85d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ExternalUserName</value>
      <webElementGuid>6a89d400-6879-44e1-b574-66fdd246a235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>1103e453-92cb-4f8b-a3c9-899d41daad00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ExternalUserName</value>
      <webElementGuid>0a1aeae9-40c7-4779-8843-5e1a727f6b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ExternalUserName&quot;)</value>
      <webElementGuid>33d0f3bc-40ea-4e36-a991-e8d4326e533e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ExternalUserName']</value>
      <webElementGuid>d2cd9e87-00c3-43a8-a73a-526b5e4204f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='CreateExportCustomerForm']/div/div[10]/input</value>
      <webElementGuid>240b0ab9-4d9b-43bb-94f3-fceb28f91695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/input</value>
      <webElementGuid>8de297f7-ddf6-43c0-b87c-33faf5ef7074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ExternalUserName' and @name = 'ExternalUserName']</value>
      <webElementGuid>8e942a98-e96b-4ea0-bc3e-ca53640fb911</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
