<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NISC ENT ID_NISC_ENT_ID</name>
   <tag></tag>
   <elementGuidId>9d71e48a-76bd-403f-8f2b-c6d3ba2a9584</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NISC_ENT_ID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NISC_ENT_ID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7de1614-5f72-45f3-aaf3-3861449657ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>31968c8d-1675-4e39-b97e-d9096b2f8b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fe76f8d2-63f5-41ca-9208-109fb95ed01e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2b65298a-9c17-4ef4-b641-92d0d6053fdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field NISC ENT ID must be a string with a maximum length of 50.</value>
      <webElementGuid>c79f1338-ccee-4538-9843-788d478214a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>5502d2f9-bd9e-4d8f-a3e7-16d782d8f8fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NISC_ENT_ID</value>
      <webElementGuid>bee0115d-184b-400f-8e84-c8e1b6ffe7a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>f9c56eca-3e8f-4ba0-ae3e-6e1bfacbc15f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NISC_ENT_ID</value>
      <webElementGuid>04aa94a7-f1ac-41cc-a73c-a54cf342c0e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NISC_ENT_ID&quot;)</value>
      <webElementGuid>cfc21bfb-71ae-40e1-b76d-876aa818f42a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NISC_ENT_ID']</value>
      <webElementGuid>488cea61-fd6a-4ca4-8751-7052e8a946aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='CreateExportCustomerForm']/div/div[26]/input</value>
      <webElementGuid>4fa23bba-1df2-4ca5-84c5-2b7996b81b0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[26]/input</value>
      <webElementGuid>3f7a31ff-a24e-472d-a07f-d1c9ac1b13a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'NISC_ENT_ID' and @name = 'NISC_ENT_ID']</value>
      <webElementGuid>b368a441-e5c7-4008-8d8e-80c5ffdbef88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
