<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TEC Error Emails_TECErrorEmails</name>
   <tag></tag>
   <elementGuidId>17fd424f-068c-429b-a500-9dbc66c7630d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TECErrorEmails</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TECErrorEmails']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75917dec-557d-4747-bcf9-bbdea7733665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bd5f53ec-d00a-48e6-b249-ef023799f71e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5bcce9e1-32d0-4744-8cfa-f7e10bb078dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>24d23ec9-bb42-4671-ba02-9d0e4361a786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field TEC Error Emails must be a string with a maximum length of 200.</value>
      <webElementGuid>824dcd2a-9cc3-4aff-8ace-512a5266b36c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>75e365ce-7ed9-4e7e-8af3-9d9625c1757f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TECErrorEmails</value>
      <webElementGuid>9576b935-3903-407c-8961-45934017fa20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>fab19859-1408-4d4e-ab8a-cde56bdecf86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TECErrorEmails</value>
      <webElementGuid>5713eaa7-d579-48fe-8bc3-25b8efbb17b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TECErrorEmails&quot;)</value>
      <webElementGuid>7ba3cdf8-336c-4d0a-b2b3-9cb84a720d95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TECErrorEmails']</value>
      <webElementGuid>ecd61f47-ba44-421f-b4f9-aa30940fc286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='CreateExportCustomerForm']/div/div[14]/input</value>
      <webElementGuid>c29b1bc2-2de8-4df0-81da-797317ff9beb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/input</value>
      <webElementGuid>ade275ef-8d18-4dab-9181-d2f32eee1e76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'TECErrorEmails' and @name = 'TECErrorEmails']</value>
      <webElementGuid>b3ebe31c-cfe8-4d5e-ba23-9f93bfc5319f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
