<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PO RegEx_PORegularExpression</name>
   <tag></tag>
   <elementGuidId>8baa8009-c13a-463b-98ff-fa144e4922bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PORegularExpression</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PORegularExpression']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>885a44d7-485c-4930-b57e-fcbccc48af0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ee571763-1036-4137-b9ec-e320297ea6d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>34cebe09-ef2c-4c31-a5c5-fda8d39668e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bcbf8c4c-6a76-4625-9345-0ad53c4a8df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field PO RegEx must be a string with a maximum length of 150.</value>
      <webElementGuid>88dcca12-f10d-4f0d-b57b-fe34c83a87ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>49bdedd9-4775-4010-9f70-6e82631757dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PORegularExpression</value>
      <webElementGuid>5b7e5bfc-0493-473e-a967-2deb5df43f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>7654b6ab-5835-4066-8a31-8a8fe75ba59b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PORegularExpression</value>
      <webElementGuid>43a1d701-1d42-4a5d-8db0-4fe72c66a87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PORegularExpression&quot;)</value>
      <webElementGuid>0b4fd673-e1dc-430c-84de-94e123ebfc1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PORegularExpression']</value>
      <webElementGuid>ff4df995-a8c6-41b7-8a03-ef7b4336f76d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='CreateExportCustomerForm']/div/div[24]/input</value>
      <webElementGuid>162f95f5-ee2b-421c-96b0-44ace4a03860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[24]/input</value>
      <webElementGuid>2b1b86ec-85fb-41dd-bd3a-03ec20203443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'PORegularExpression' and @name = 'PORegularExpression']</value>
      <webElementGuid>a6da3f2e-bdc7-4be0-afa9-eaa83651b79f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
