<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>li_DAFFRON</description>
   <name>li_DAFFRON</name>
   <tag></tag>
   <elementGuidId>91273d16-0cc8-4525-a2e7-a9207aee41f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[contains(@id,'DelayedExportType_listbox')]//li[normalize-space()='DAFFRON']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
