<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_NO_k-switch-thumb k-rounded-full_1_2_3_4_5_6_7</name>
   <tag></tag>
   <elementGuidId>854fa223-530e-4a9a-8008-82d4670828ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.k-switch.k-switch-md.k-rounded-full.k-switch-off > span.k-switch-thumb-wrap > span.k-switch-thumb.k-rounded-full</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='CreateExportCustomerForm']/div/div[21]/span/span[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>eec848e4-3e03-45ad-a594-3288a3a64d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-switch-thumb k-rounded-full</value>
      <webElementGuid>366e5184-bca6-464b-8072-88de526161f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CreateExportCustomerForm&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 mb-3&quot;]/span[@class=&quot;k-switch k-switch-md k-rounded-full k-switch-off&quot;]/span[@class=&quot;k-switch-thumb-wrap&quot;]/span[@class=&quot;k-switch-thumb k-rounded-full&quot;]</value>
      <webElementGuid>d847bb8a-a559-4670-86a7-6f4d2d5932c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='CreateExportCustomerForm']/div/div[21]/span/span[2]/span</value>
      <webElementGuid>e795957c-5669-4534-89b3-1332f89e859b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/span/span[2]/span</value>
      <webElementGuid>7821b65f-81e8-47a3-8af4-97bcb9d84d06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
