<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//span[normalize-space()='View']</description>
   <name>button_View</name>
   <tag></tag>
   <elementGuidId>b4a7f76c-dd3a-4339-8ba6-063c001385d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[normalize-space()='View']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
