<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Upload</name>
   <tag></tag>
   <elementGuidId>d01e3c89-757f-4797-ad86-2cc39c24feb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.k-upload-selected.k-button.k-button-md.k-rounded-md.k-button-solid.k-button-solid-primary</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@class='k-upload-selected k-button k-button-md k-rounded-md k-button-solid k-button-solid-primary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5819e471-f240-4438-aa4e-3631b127b2a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-upload-selected k-button k-button-md k-rounded-md k-button-solid k-button-solid-primary</value>
      <webElementGuid>34c368fe-d463-4b46-8a2d-2eba64052ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4a7c4107-2312-4e19-bade-be2b9b419546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload</value>
      <webElementGuid>72f11f17-05bd-466b-9465-436001c6d2af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;upload-enabled-wrapper&quot;)/div[@class=&quot;k-upload k-upload-async&quot;]/div[@class=&quot;k-actions&quot;]/button[@class=&quot;k-upload-selected k-button k-button-md k-rounded-md k-button-solid k-button-solid-primary&quot;]</value>
      <webElementGuid>7dfb0011-0cbf-4486-afb3-dc1f6b67ba06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>1ca8cddd-e40a-44ac-b790-31674f3812dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='upload-enabled-wrapper']/div/div[2]/button</value>
      <webElementGuid>51ea7b89-7abc-44d8-8635-bfa2d55d2c0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PersonalData.csv'])[1]/following::button[2]</value>
      <webElementGuid>b11086c8-17cf-4d9c-a8a7-31251dfb6532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drop files here to upload'])[1]/following::button[2]</value>
      <webElementGuid>932ba23c-c37d-401e-bac7-4f75c684a32a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[1]/preceding::button[1]</value>
      <webElementGuid>81372f94-cb67-4096-b867-d48265db7470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>3ed98946-df0d-477e-b097-c46ccd4a2356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Upload' or . = 'Upload')]</value>
      <webElementGuid>e5b0c3bc-bfe3-4d54-8618-a59521d9b319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[contains(@class, 'k-grid-Process')]</value>
      <webElementGuid>d5750dba-239a-4a47-a5fa-24aa11300174</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
