<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Auto Updates_k-input-inner</name>
   <tag></tag>
   <elementGuidId>940dc570-d170-4d05-99aa-dc581f3eecce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.k-input-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=searchbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1caef6e-6788-43ea-8fc4-b9814c7b1f2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input-inner</value>
      <webElementGuid>5783ce7c-f9ef-4c05-954a-c16eb6186354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aec44a17-429c-4f08-91b2-3d4d1d2ed7c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>searchbox</value>
      <webElementGuid>d92763f0-55f7-4b58-a9ea-27d0408c3950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>b8036e53-33d5-4cfa-86a7-d149bcb7e0d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>33affbec-cc2c-4b44-945f-87ccf47adff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>99679575-1a4f-4055-a065-d1841f831d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>46159913-33bb-4aab-97bf-ab28a6ae50e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>69ca44ef-0981-47d0-a0c1-541b61441626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>SelectedProphet21ID_listbox</value>
      <webElementGuid>dd8c7c8f-907b-4c35-8b90-e3d8fb92be36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>bbcfa488-1b75-42c5-9844-5834b78a4596</value>
      <webElementGuid>e362082a-a660-449f-b5eb-a675c82f9bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;k-webkit k-webkit139 mdl-js&quot;]/body[@class=&quot;page-header-fixed sidemenu-closed-hidelogo page-content-white page-md white-color white-sidebar-color logo-white header-white&quot;]/div[@class=&quot;k-animation-container k-animation-container-shown&quot;]/div[@class=&quot;k-child-animation-container&quot;]/div[@class=&quot;k-list-container k-popup&quot;]/div[@class=&quot;k-list-filter&quot;]/span[@class=&quot;k-searchbox k-input k-input-md k-rounded-md k-input-solid&quot;]/input[@class=&quot;k-input-inner&quot;]</value>
      <webElementGuid>356bc8c4-da78-4a65-bb5b-ec60f4df029f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[3]</value>
      <webElementGuid>5558b585-fabe-48a7-892f-19d046142ebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/span/input</value>
      <webElementGuid>fe66ea89-f73e-42b4-910b-61b44c6e7dbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>9e2e140a-c59c-4cd8-82e3-76a293bf3609</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
