<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No data found_k-input-inner</name>
   <tag></tag>
   <elementGuidId>c6d48fd6-089c-4d0c-b6d0-3fb4b2ac82b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.k-animation-container.k-animation-container-shown > div.k-child-animation-container > div.k-list-container.k-popup > div.k-list-filter > span.k-searchbox.k-input.k-input-md.k-rounded-md.k-input-solid > input.k-input-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=searchbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>26f95bcb-c9a3-4ece-8f72-31c8f12d9990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input-inner</value>
      <webElementGuid>717e6efe-29de-4b7a-8014-5da2184b4055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5e10a3f1-a2d6-466b-86af-542542037055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>searchbox</value>
      <webElementGuid>9c42d5f8-5b82-4912-85b5-cf865f6d9191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>430dccb5-8bb5-401f-aebd-7fc49eddbde1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>b32f777e-435e-43c9-b8b6-ee54ec14d187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b620cacd-6147-491d-8ae0-7de7a297bda1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>eb56a747-ecd6-465b-a407-c67a613d0640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>94054821-db97-4275-9e66-c378583814b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>SelectedTECLocation_listbox</value>
      <webElementGuid>f97406b6-2505-4da3-873a-b72985f5fe36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>dea5142a-66b5-43c2-b595-1d9e53544340</value>
      <webElementGuid>aca73261-ea9c-4c7c-b0be-a166cbeede14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;k-webkit k-webkit139 mdl-js&quot;]/body[@class=&quot;page-header-fixed sidemenu-closed-hidelogo page-content-white page-md white-color white-sidebar-color logo-white header-white&quot;]/div[@class=&quot;k-animation-container k-animation-container-shown&quot;]/div[@class=&quot;k-child-animation-container&quot;]/div[@class=&quot;k-list-container k-popup&quot;]/div[@class=&quot;k-list-filter&quot;]/span[@class=&quot;k-searchbox k-input k-input-md k-rounded-md k-input-solid&quot;]/input[@class=&quot;k-input-inner&quot;]</value>
      <webElementGuid>bcef18a8-0785-4fe2-9c75-a30bf3df333d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[4]</value>
      <webElementGuid>b80e9e16-575e-44e0-a03f-69f24ace1cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/span/input</value>
      <webElementGuid>c586fd2b-0f0a-4b23-9f37-b838e082edb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>161cbcca-dc0c-42d4-818e-b0af66f8f7be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
