<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select Customer</name>
   <tag></tag>
   <elementGuidId>08542fe6-edcc-4201-aa98-eb9b3c299a1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.k-input-value-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[contains(text(),'Select Customer...')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f8c31066-d1b7-433d-abb8-647a5663d7eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input-value-text</value>
      <webElementGuid>b4cf3d19-2c5f-4473-a239-ea5fa396dd90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Customer...</value>
      <webElementGuid>466f0c02-118a-4ff5-bf86-669a7e72f5e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ca26dbc2-7abc-4533-a4ce-1308940189eb&quot;)/span[@class=&quot;k-input-value-text&quot;]</value>
      <webElementGuid>35f42edb-62b2-4a7a-8a39-894d5338daa0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='ca26dbc2-7abc-4533-a4ce-1308940189eb']/span</value>
      <webElementGuid>c35f5be7-be8c-4947-b27c-0193f60c0624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Customer'])[1]/following::span[3]</value>
      <webElementGuid>91c57f06-eca2-4852-963e-f4f71d6da87d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Environment Settings'])[1]/following::span[4]</value>
      <webElementGuid>dffcfd33-6d28-4dd8-ac7f-2e29dece78d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Location'])[1]/preceding::span[4]</value>
      <webElementGuid>fc44f98c-a07e-49cb-996b-48373232373d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Location...'])[1]/preceding::span[4]</value>
      <webElementGuid>44f11110-6ea0-4686-bad9-cd43673cc78a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select Customer...']/parent::*</value>
      <webElementGuid>c3e4211e-72d8-4b8e-98b5-4c29660207c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span</value>
      <webElementGuid>0b565811-8187-46d5-86fd-dfad89b89101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Select Customer...' or . = 'Select Customer...')]</value>
      <webElementGuid>59c206df-c6e0-4875-96af-8007d5735d38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//span[contains(text(),'Select Customer...')]</value>
      <webElementGuid>91f88651-ebc1-4799-aabd-50b6fcacc16d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
