<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_absgmail.com</name>
   <tag></tag>
   <elementGuidId>f609728c-9e72-45b6-adab-9e26074ee5a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='e5f0a070-1539-46e7-9010-cac8867e7f4e']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.k-list-item-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b6a584ae-2951-4971-a244-c4773454c577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-list-item-text</value>
      <webElementGuid>6df48165-6273-48c5-977c-619a057235d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>abs@gmail.com</value>
      <webElementGuid>bbcc414e-6da5-456a-94d4-4435ea78db33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e5f0a070-1539-46e7-9010-cac8867e7f4e&quot;)/span[@class=&quot;k-list-item-text&quot;]</value>
      <webElementGuid>6555a387-4be5-4262-9581-08c7b337d18d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='e5f0a070-1539-46e7-9010-cac8867e7f4e']/span</value>
      <webElementGuid>ab548feb-2e2e-4c38-9eda-3dfe04bda213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto Updates'])[1]/following::span[5]</value>
      <webElementGuid>63af7de4-cb67-4571-b65a-c89a57886763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save Histry'])[1]/following::span[8]</value>
      <webElementGuid>aa08fc0c-a24a-474a-afad-fda159da1a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data found.'])[1]/preceding::span[1]</value>
      <webElementGuid>becf763b-67aa-426c-b66a-d17e9053525d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/span</value>
      <webElementGuid>1c425637-8b9d-445b-be33-6eb1f4d4637b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'abs@gmail.com' or . = 'abs@gmail.com')]</value>
      <webElementGuid>ef036bf3-ddb4-4d41-a7eb-ab1518e8d818</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
