<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_ashishsupport.xcellence-it.com_wd-break</name>
   <tag></tag>
   <elementGuidId>52be6add-d945-4470-97b1-e3d8bb87f8a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='a24bb203-dc9e-415a-9f1f-8319c68c62dc']/tr[2]/td[2]/table/tbody/tr[12]/td[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;kashyap.padhiyar@support.xcellence-it.com&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>42200ece-3732-4c5e-b3c3-a0ef845f789f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wd-break</value>
      <webElementGuid>ed0a0161-c810-48e1-b659-f38ece357f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>kashyap.padhiyar@support.xcellence-it.com</value>
      <webElementGuid>a2b16455-2abc-4d96-8878-a74dd0ffd1c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a24bb203-dc9e-415a-9f1f-8319c68c62dc&quot;)/tr[@class=&quot;k-detail-row k-table-row&quot;]/td[@class=&quot;k-table-td k-detail-cell&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[12]/td[@class=&quot;wd-break&quot;]</value>
      <webElementGuid>79656285-6d6e-4ba5-9d5b-0f74b9fcbd1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='a24bb203-dc9e-415a-9f1f-8319c68c62dc']/tr[2]/td[2]/table/tbody/tr[12]/td[3]</value>
      <webElementGuid>18b94ad7-ef02-4a2c-a4d8-c5e8e754f9f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ashish@support.xcellence-it.com'])[1]/following::td[1]</value>
      <webElementGuid>e1b7d0ba-b466-468a-9a53-d532b9124fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UpdatedBy'])[1]/following::td[2]</value>
      <webElementGuid>d8599d6c-ce3d-4dc0-ab04-70d26c27212a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DateUpdated'])[1]/preceding::td[1]</value>
      <webElementGuid>aa8cfdf5-ef00-4391-a404-2693aeecf45f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='items per page'])[1]/preceding::td[4]</value>
      <webElementGuid>c0299d3b-22ab-4446-bff0-ba0745ddd340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='kashyap.padhiyar@support.xcellence-it.com']/parent::*</value>
      <webElementGuid>1fbc7faa-8404-41ed-8ae8-3ed664268975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[12]/td[3]</value>
      <webElementGuid>76fa4ead-8143-47e7-ad62-65c24eb583ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'kashyap.padhiyar@support.xcellence-it.com' or . = 'kashyap.padhiyar@support.xcellence-it.com')]</value>
      <webElementGuid>c9d83a69-5ff0-45fc-8a5f-5819b5fa0ea6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
