<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_UpdatedBy_wd-break</name>
   <tag></tag>
   <elementGuidId>c04b6ab9-0bf6-4de4-9cd6-ca31dc9d9213</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[normalize-space()='UpdatedBy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;ashish@support.xcellence-it.com&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>cee1a4ee-ed0f-46b1-934e-d74e46bd2ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wd-break</value>
      <webElementGuid>636142fa-6bc8-4c60-97b8-93c8efbcd346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ashish@support.xcellence-it.com</value>
      <webElementGuid>1b09001f-f54b-49b0-b5ba-be0d54af77b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a24bb203-dc9e-415a-9f1f-8319c68c62dc&quot;)/tr[@class=&quot;k-detail-row k-table-row&quot;]/td[@class=&quot;k-table-td k-detail-cell&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[12]/td[@class=&quot;wd-break&quot;]</value>
      <webElementGuid>f5585218-d494-4180-af9e-c437e800daf7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='a24bb203-dc9e-415a-9f1f-8319c68c62dc']/tr[2]/td[2]/table/tbody/tr[12]/td[2]</value>
      <webElementGuid>03cb4b53-8cf5-4c99-b72c-f0c61610fa38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UpdatedBy'])[1]/following::td[1]</value>
      <webElementGuid>93a9d570-ab76-4396-9178-c125c4e9fadc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='True'])[9]/following::td[2]</value>
      <webElementGuid>38097ba8-b0c9-436d-b14f-47b4f086b5fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kashyap.padhiyar@support.xcellence-it.com'])[1]/preceding::td[1]</value>
      <webElementGuid>d51130f5-3a7b-477f-b4c4-e99b2c77e459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DateUpdated'])[1]/preceding::td[2]</value>
      <webElementGuid>8f3e5546-4680-4ca8-9a96-10533ca71f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ashish@support.xcellence-it.com']/parent::*</value>
      <webElementGuid>7184f787-ea90-45cc-859d-56bf03a1b19c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[12]/td[2]</value>
      <webElementGuid>6dbef744-cc23-46cc-b67f-a6029a5df528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'ashish@support.xcellence-it.com' or . = 'ashish@support.xcellence-it.com')]</value>
      <webElementGuid>82a7c149-181b-4b84-97bd-d2d60bc4dbe4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
