<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select Customer_k-input-value-text_1</name>
   <tag></tag>
   <elementGuidId>692dfac8-b40c-4cf2-8bbe-cab2524e63d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.k-input-value-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='f410f984-b59e-4aa9-a941-2ff4b1af6aac']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#page-body-content >> internal:text=&quot;LPT004&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1c8715f8-e6c7-4342-9318-e6de0c562f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input-value-text</value>
      <webElementGuid>397db608-7916-45d0-b5d4-fb572bf82525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LPT004</value>
      <webElementGuid>196504f8-90cc-4341-8f6e-bc2a469db067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f410f984-b59e-4aa9-a941-2ff4b1af6aac&quot;)/span[@class=&quot;k-input-value-text&quot;]</value>
      <webElementGuid>6a5c02fb-a4c8-495e-8c44-28d51373a950</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='f410f984-b59e-4aa9-a941-2ff4b1af6aac']/span</value>
      <webElementGuid>4c09cd39-b2c5-4690-9c7e-66762610f78b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Customer'])[1]/following::span[3]</value>
      <webElementGuid>d5966bd8-fb64-4679-af3b-4579528834f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Environment Settings'])[1]/following::span[4]</value>
      <webElementGuid>7c20c413-17dc-4751-ae1b-282a5ddc76b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Location'])[1]/preceding::span[4]</value>
      <webElementGuid>f59e1858-e5b5-401d-b212-9458a73469bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Location...'])[1]/preceding::span[4]</value>
      <webElementGuid>803eb7ba-adf3-4c68-a40d-a0bd434d5c70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LPT004']/parent::*</value>
      <webElementGuid>75fc19ad-2a34-48f5-b5bc-d910bd0678be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span</value>
      <webElementGuid>6cfd5ed4-5f05-41fa-aa8f-e0108f45cdf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'LPT004' or . = 'LPT004')]</value>
      <webElementGuid>0ca6368d-3ae4-4929-b4ae-b080ab443421</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
