<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Click_here_for_audit_log</description>
   <name>Click_here_for_audit_log</name>
   <tag></tag>
   <elementGuidId>2284fc42-dbbd-44fe-ac80-4eac72c8fd43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div//div//div//button[@id='btnaudit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
