<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>edit_button</description>
   <name>edit_button</name>
   <tag></tag>
   <elementGuidId>334f7f6f-a98c-4ad7-834b-fbea77f8172e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tbody/tr[1]/td[1]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
