<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Or_k-button k-button-md k-rounded-md_b8e9d9</name>
   <tag></tag>
   <elementGuidId>6eca2be1-9b9d-4995-8098-b8958ca1a98c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.k-button.k-button-md.k-rounded-md.k-button-solid.k-button-solid-base.k-icon-button.k-toolbar-button.k-toolbar-tool.k-focus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9c16263b-71db-4e6c-a6e2-cc9973ab318d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>de26aa5b-54c9-40a8-bb26-c4bbed71a74d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-button k-button-md k-rounded-md k-button-solid k-button-solid-base k-icon-button k-toolbar-button k-toolbar-tool k-focus</value>
      <webElementGuid>8e8cf499-59c8-4c03-93f7-363348dcd66e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>df3536be-6502-4623-bc12-e6665d7269c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5752d889-73fc-4766-9a5e-559996b23b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>95ecab73-2fc1-4b80-aadc-d04a930fafbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>98fa1f04-c138-4911-b930-56df1479acab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-command</name>
      <type>Main</type>
      <value>expression</value>
      <webElementGuid>4878e30a-5083-4c17-ada7-d0027777a433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add Expression</value>
      <webElementGuid>a9855418-b544-4220-b5a3-1215f3875e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Add Expression</value>
      <webElementGuid>82a3f41d-cc0e-426e-aa2f-4fb2da02fab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uid</name>
      <type>Main</type>
      <value>a1fc2c2f-c887-43fa-9bb9-d7b9bb1a9314</value>
      <webElementGuid>2afcc369-f3ac-4bdd-b4e3-52397b82f100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d75d69e5-187d-444b-8ab4-58ee881ad27c&quot;)/button[@class=&quot;k-button k-button-md k-rounded-md k-button-solid k-button-solid-base k-icon-button k-toolbar-button k-toolbar-tool k-focus&quot;]</value>
      <webElementGuid>ef831743-c3e4-41f1-a3af-2db53b632b55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>0caf870f-8e6f-41fb-ba3b-48722fb4c976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='d75d69e5-187d-444b-8ab4-58ee881ad27c']/button</value>
      <webElementGuid>6fcde36f-273c-401e-bca9-fc0db6c36e18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Or'])[1]/following::button[1]</value>
      <webElementGuid>567af982-9310-4c29-8d39-9dddc1b1a473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='And'])[1]/following::button[2]</value>
      <webElementGuid>6b387440-87a5-414a-ae10-ccc84dbd14a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/preceding::button[3]</value>
      <webElementGuid>fa739103-5659-46b9-b5a2-7c8614e7ea1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/button</value>
      <webElementGuid>18e62603-da53-465e-9554-c842fff5894f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Add Expression']</value>
      <webElementGuid>36450269-cb2f-4dca-ab39-e6bd20835432</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
