<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>firstdropdown</description>
   <name>firstdropdown</name>
   <tag></tag>
   <elementGuidId>083d8bef-76a2-449e-bbef-d64ee3b3faf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@title='Fields']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
