<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Is equal to_ecc280c7-73f0-440e-98d5-a_67587d</name>
   <tag></tag>
   <elementGuidId>acdad634-10e9-453a-8480-3d978121aca8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ecc280c7-73f0-440e-98d5-a17b7365f684']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ecc280c7-73f0-440e-98d5-a17b7365f684</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f3dd72a-ae98-404f-b9b0-6cf157098668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e7db5799-befe-436a-8904-30908fdce457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ecc280c7-73f0-440e-98d5-a17b7365f684</value>
      <webElementGuid>b4f36d10-71d3-4e96-a9cb-42909bb2815c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-checkbox k-checkbox-md k-rounded-md</value>
      <webElementGuid>322dcd4f-0738-4dfe-a629-a81f2b9e8f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Delayed</value>
      <webElementGuid>eeefdefd-2ef8-4ff7-8d45-ebb26e3551fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b44fb04a-3bec-4206-8ab1-d88245afa9ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>checked: value</value>
      <webElementGuid>3e4221e0-80b0-4ebe-bdef-1ad5cbd629bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d1b6f0fb-001a-4945-9ce7-90cb187b91c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ecc280c7-73f0-440e-98d5-a17b7365f684&quot;)</value>
      <webElementGuid>1df12592-9886-4e4c-93f0-1b27e9b003b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ecc280c7-73f0-440e-98d5-a17b7365f684']</value>
      <webElementGuid>f951dcbe-afd5-4605-b91e-814f0eb3846c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a16af6c9-afcb-4371-940d-ad5a08670a0b']/div/input</value>
      <webElementGuid>f10ce8a9-eee8-495f-9e8b-6259453f4d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>497c0e09-52bb-4ead-8717-ad1654d444ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ecc280c7-73f0-440e-98d5-a17b7365f684' and @type = 'checkbox']</value>
      <webElementGuid>9069b366-5aaa-435d-888b-a65cf006338a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
