<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contains_ac8c313d-1f5e-4516-a332-0efa_59a3b4</name>
   <tag></tag>
   <elementGuidId>689b584a-fba7-47fb-899e-45fd13b81341</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ac8c313d-1f5e-4516-a332-0efae5c449ea']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ac8c313d-1f5e-4516-a332-0efae5c449ea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>228c019b-cdbb-4a42-beed-3677cac40b16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>1b7d9bde-9dc5-4353-9d4c-53426a1fd5de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ac8c313d-1f5e-4516-a332-0efae5c449ea</value>
      <webElementGuid>d61a6520-02e3-4ee9-aeec-53e69894fa36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1aa7b28f-7c73-4744-9a87-edd74112a9cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>TECCustomerNumber</value>
      <webElementGuid>5dad9b98-c823-4cd2-8851-76b6cfed0686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>TECCustomerNumber</value>
      <webElementGuid>4c1efad9-286d-4bdc-8b45-7cd8ae993b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input-inner</value>
      <webElementGuid>c92a32af-4477-4d27-8215-52a754413d2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value: value</value>
      <webElementGuid>9d70f4b4-d3ba-43f8-a1e5-4d32203f3b8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ac8c313d-1f5e-4516-a332-0efae5c449ea&quot;)</value>
      <webElementGuid>e59de4fb-6f32-4cc8-af4f-38cdda4ad048</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ac8c313d-1f5e-4516-a332-0efae5c449ea']</value>
      <webElementGuid>905cf852-13b6-4536-a216-4ea38073af12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='baa1e7aa-7b88-4317-98ab-731eb3da1b3a']/div/span/input</value>
      <webElementGuid>68d5148f-825f-4cf5-81ea-6e1d2cfda6a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>eb01466f-bdc6-4d9b-b954-6c75d26127dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ac8c313d-1f5e-4516-a332-0efae5c449ea' and @type = 'text' and @title = 'TECCustomerNumber']</value>
      <webElementGuid>a3f92822-2f7d-41fb-ac1e-764830790b36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
