<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Is equal to_e6046f64-d75e-43b0-9abd-b_c3829e</name>
   <tag></tag>
   <elementGuidId>5f961549-be0f-43bf-9013-272aecdb9d6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='e6046f64-d75e-43b0-9abd-bc74edb83585']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e6046f64-d75e-43b0-9abd-bc74edb83585</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8b184b0c-7e37-4e95-9597-e2e41287227b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f330ed32-d221-4ddb-96f3-90c115f08317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e6046f64-d75e-43b0-9abd-bc74edb83585</value>
      <webElementGuid>f1763779-4f6e-4227-8c59-b078625840ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>68ce6c57-6beb-479d-97d2-20a110aec2a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>DocumentType</value>
      <webElementGuid>74196ddb-79d8-4e43-9de0-1e2f6751cc15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>DocumentType</value>
      <webElementGuid>189c38fc-6529-4141-b117-570599de6428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>numerictextbox</value>
      <webElementGuid>bd6c2d09-af4b-4a66-a9bd-65c9e9128a36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value: value</value>
      <webElementGuid>951f711c-ce03-4c58-8d39-24be77c3dc73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>spinbutton</value>
      <webElementGuid>0051ac35-3db6-49fa-bd3f-f972cfc776c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input-inner</value>
      <webElementGuid>e92f547f-c776-46a4-ada3-61565f614b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e6bbf0a5-89df-438e-9759-23b408ac83bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuenow</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>99c357db-f317-4436-bb6a-16068d402394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e6046f64-d75e-43b0-9abd-bc74edb83585&quot;)</value>
      <webElementGuid>187424d5-5acd-4d02-a82e-eb1b1600d795</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='e6046f64-d75e-43b0-9abd-bc74edb83585']</value>
      <webElementGuid>2740b84b-c95a-4a9b-83f9-1b3be3a38a78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a1749992-6d7c-4019-b444-50750da8f875']/div/span/input[2]</value>
      <webElementGuid>d8372f26-bd47-4d2c-9b1d-45894da86108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>271c0c77-6cd1-4006-97ef-01e19ace5a52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'e6046f64-d75e-43b0-9abd-bc74edb83585' and @type = 'text' and @title = 'DocumentType']</value>
      <webElementGuid>30001a73-a419-4192-85a5-0d139fa7e69e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
