<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Is not equal to_ab2eeeaf-3dae-4be3-bf_20120d</name>
   <tag></tag>
   <elementGuidId>cf2079d7-517c-461f-a38a-1fe222fc93e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ab2eeeaf-3dae-4be3-bf6c-67e439c961ca']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ab2eeeaf-3dae-4be3-bf6c-67e439c961ca</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>88d7aeaa-15ac-45f6-9223-2e63c229b86b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>91733b34-d3e0-4e56-a64e-b8e58c682865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ab2eeeaf-3dae-4be3-bf6c-67e439c961ca</value>
      <webElementGuid>64fbe2db-32ad-411b-b219-285e088da829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>da160709-e6ac-4ce5-beda-67278fc17159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>TECCustomerNumber</value>
      <webElementGuid>7039af4e-63d6-4686-95a4-046f0d436bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>TECCustomerNumber</value>
      <webElementGuid>454d0e43-39a3-4b08-af50-e0f5c2b0dd0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input-inner</value>
      <webElementGuid>f2c8d40d-acbc-467f-9998-2b243e254cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value: value</value>
      <webElementGuid>3f2d3929-9cbd-433c-98c6-74c984d1dd57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ab2eeeaf-3dae-4be3-bf6c-67e439c961ca&quot;)</value>
      <webElementGuid>21a3779e-5104-4379-b98d-d8852996715b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ab2eeeaf-3dae-4be3-bf6c-67e439c961ca']</value>
      <webElementGuid>020bce7e-9271-4125-a2ed-8d99a064eec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eda6a16d-00b4-40a4-8c2e-567182823ed1']/div/span/input</value>
      <webElementGuid>6cda88e3-d0f7-4a97-a438-e0f71716da62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>d071be65-e0e6-41da-8914-261b74bb2e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ab2eeeaf-3dae-4be3-bf6c-67e439c961ca' and @type = 'text' and @title = 'TECCustomerNumber']</value>
      <webElementGuid>8e85f7bb-ccce-4125-af18-72c0482abca8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
