<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Is equal to_b505bd87-bc61-43c6-ba6f-6_49fbf8</name>
   <tag></tag>
   <elementGuidId>cd2a1e1f-926e-455e-a396-2f123d1cd442</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@data-validate='false' and @type='text' and @title='DocumentType']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b505bd87-bc61-43c6-ba6f-6705415cc102</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>11946530-a4a1-4a95-a243-71f0e97ca9ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>4c10b14e-848c-419f-add6-bfa109d49d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b505bd87-bc61-43c6-ba6f-6705415cc102</value>
      <webElementGuid>32ad2fea-d670-4deb-9652-5b03011456b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>473eaa48-13b5-49b3-8c70-6d630a480baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>DocumentNumber</value>
      <webElementGuid>0304bfe7-0525-47eb-846d-3caa4fd636bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>DocumentNumber</value>
      <webElementGuid>477f398b-96c2-4817-8505-3e628608c29a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input-inner</value>
      <webElementGuid>ff97e398-297f-4f96-b197-d3be5712e405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value: value</value>
      <webElementGuid>17b6a1de-4f73-4747-b050-6a26743a34ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b505bd87-bc61-43c6-ba6f-6705415cc102&quot;)</value>
      <webElementGuid>b5f22441-34ff-4605-9d03-b8f4efc9680f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b505bd87-bc61-43c6-ba6f-6705415cc102']</value>
      <webElementGuid>fdbc6f83-d124-496c-8dfd-dfb2e1d3285b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bb623c1f-d22d-467f-8576-29d4d08f72c4']/div/span/input</value>
      <webElementGuid>4c9fe6f8-1325-4919-8b47-9a52cf109603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>ead52c2d-df7a-4e59-8166-019a73c6a8b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'b505bd87-bc61-43c6-ba6f-6705415cc102' and @type = 'text' and @title = 'DocumentNumber']</value>
      <webElementGuid>1c1658aa-278c-4193-b8fb-820a42971b43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
