<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Has Document_k-select-checkbox k-chec_bdcdac_1_2</name>
   <tag></tag>
   <elementGuidId>f0d31379-c48b-4f8f-b667-9f3265de00e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#locked_datacell_3_0 > input.k-select-checkbox.k-checkbox.k-checkbox-md.k-rounded-md</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65dc5029-a600-41fb-a906-c7b4e2655a7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>41b51102-88e8-4589-b11b-97ee4ac230f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-select-checkbox k-checkbox k-checkbox-md k-rounded-md</value>
      <webElementGuid>d2e9e5be-da70-482f-b131-eeb990cce91f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2cc47f98-d473-4ebb-9ee4-556914ac75e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select row</value>
      <webElementGuid>b8e7d49f-5568-4b56-b600-4a86e5a1d1e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c57fa136-7b6b-48e0-b9cb-1e9f93f8e212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a02d10a9-b1b2-4f67-aef6-b17381700402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locked_datacell_3_0&quot;)/input[@class=&quot;k-select-checkbox k-checkbox k-checkbox-md k-rounded-md&quot;]</value>
      <webElementGuid>ba959ce8-468f-4cd3-acdf-ccc2679bf768</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[5]</value>
      <webElementGuid>0834408c-c81b-4745-92cf-1572b412fa2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='locked_datacell_3_0']/input</value>
      <webElementGuid>e38cde6b-2b5b-4c5e-9ec7-c577b119d84e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/input</value>
      <webElementGuid>a64fb7ee-b25f-4663-8897-807ecd10c927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>1c667b9a-7c80-4a61-98f4-d18d885d7bd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
