<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Has Document_k-select-checkbox k-chec_bdcdac_1_2_3</name>
   <tag></tag>
   <elementGuidId>385a3f84-ac03-4516-bc7e-7663ae040a36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#locked_datacell_4_0 > input.k-select-checkbox.k-checkbox.k-checkbox-md.k-rounded-md</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0efd0943-bca1-4ef6-933d-973c54fc0747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>16fc16d0-4caf-4563-9e01-d4230827be13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-select-checkbox k-checkbox k-checkbox-md k-rounded-md</value>
      <webElementGuid>991cbff9-3d93-4fad-a59b-14ece3f4cd17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8c4ed929-3f68-4214-b5eb-6ad87e04852b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select row</value>
      <webElementGuid>dca35141-61bf-4f40-86c2-5828e9b5b36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7ae23276-445e-4377-8c0f-2e4795613629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0b010de5-4d3a-4a65-bd99-68f8fa7b891c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locked_datacell_4_0&quot;)/input[@class=&quot;k-select-checkbox k-checkbox k-checkbox-md k-rounded-md&quot;]</value>
      <webElementGuid>c1649cc3-de23-4c5e-8f99-d63f7b6211bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[6]</value>
      <webElementGuid>0074a303-dce4-4bf3-b95c-4e1d1cc22637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='locked_datacell_4_0']/input</value>
      <webElementGuid>05bc165a-e64c-4874-a952-273c304baa49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/input</value>
      <webElementGuid>7477b520-219c-4051-960e-b24161ecb47c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>8edd7c95-c1bb-4c55-800d-ab14808de7aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
