<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Is equal to_1</name>
   <tag></tag>
   <elementGuidId>6099de72-0f1a-40c7-8c99-17a7e2a543c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='c75102fe-e5fc-41a6-add8-6704515684b4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c75102fe-e5fc-41a6-add8-6704515684b4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>28855938-90a5-4a3c-8c1b-5ba748f8b1a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>097a6eae-4e52-4de2-a0f0-046688ded94d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d19fa5e2-194f-4006-a2a5-12a6f025488f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>77d61924-b12a-4a95-8c53-f90dd5236e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-list-item k-selected k-focus k-hover</value>
      <webElementGuid>014547bd-82e6-467c-8323-c9ac7835e81d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0a22bc88-f7b4-46d8-98e8-e0001c9e986a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-offset-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3fe9be2d-1c36-4efe-9478-09a2c13f66a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c75102fe-e5fc-41a6-add8-6704515684b4</value>
      <webElementGuid>0f6564cd-bbc6-40f2-b282-33befff59152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Is equal to</value>
      <webElementGuid>a95e3a9b-58b8-4380-84e9-808f3ab9a812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c75102fe-e5fc-41a6-add8-6704515684b4&quot;)</value>
      <webElementGuid>3010fa7c-3762-415e-89f5-1950d9a7e3d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='c75102fe-e5fc-41a6-add8-6704515684b4']</value>
      <webElementGuid>e8695555-8601-446a-8847-22c5615c7ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='af3046fb-3393-42a4-bf71-b44e9300234b_listbox']/li</value>
      <webElementGuid>bd5bb3cb-dd4e-41d5-979f-ccd41d1a6510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data found.'])[2]/following::li[1]</value>
      <webElementGuid>b86ec360-b400-4c37-8728-d583ca6b617e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Processed Date'])[2]/following::li[1]</value>
      <webElementGuid>bef54ec7-25fe-406d-b772-267fe68a5762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is not equal to'])[2]/preceding::li[1]</value>
      <webElementGuid>09f273d8-9390-4b83-ac4e-1e9b7435b8e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/ul/li</value>
      <webElementGuid>6ede5732-6af7-482b-9323-46afa6d5dfb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'c75102fe-e5fc-41a6-add8-6704515684b4' and (text() = 'Is equal to' or . = 'Is equal to')]</value>
      <webElementGuid>20be5d59-789c-4247-9557-397429dc6513</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
