<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Is equal to</name>
   <tag></tag>
   <elementGuidId>f6e05c82-f9c6-4b7e-b373-33aa9c774b4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='f29df585-b8d7-4d7b-8b5b-cd2bfba50e57']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#f29df585-b8d7-4d7b-8b5b-cd2bfba50e57</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>4884eff2-73e5-4e54-9223-daf8f982093d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9c6134dc-789c-44fc-9cfc-39d6bdfbfd2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>be7544b7-93b5-4214-9619-50ccd012787f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>d06f9e9a-148c-40a2-a91b-a61a85d22444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-list-item k-selected k-focus k-hover</value>
      <webElementGuid>b6518d3c-5da0-4aab-959e-f392a717c0f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f2570b13-161b-4309-a17e-82cd68c98108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-offset-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7252dfb4-97a2-4ceb-8d78-5776e5ac4dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f29df585-b8d7-4d7b-8b5b-cd2bfba50e57</value>
      <webElementGuid>a26ab62e-35bf-4cb3-be20-57040a50ef46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Is equal to</value>
      <webElementGuid>e1aec042-9a58-4295-bb81-59f496632139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f29df585-b8d7-4d7b-8b5b-cd2bfba50e57&quot;)</value>
      <webElementGuid>6087c7bd-6233-4240-821b-5f7fb6e217bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='f29df585-b8d7-4d7b-8b5b-cd2bfba50e57']</value>
      <webElementGuid>e3407e62-727a-4e4d-a277-e454c8645f22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='be8a9c82-bd03-49ad-8aa4-341ee7d0615a_listbox']/li</value>
      <webElementGuid>b76d1f3e-1f15-4fe5-92cb-2bd2e09a5cc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data found.'])[2]/following::li[1]</value>
      <webElementGuid>83a8c44d-9d39-4117-b0c3-f053172225ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Processed Date'])[2]/following::li[1]</value>
      <webElementGuid>89f3c793-42c3-4b30-b7ea-570f0fe92715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is not equal to'])[2]/preceding::li[1]</value>
      <webElementGuid>a307a199-c86d-4599-b8d3-e2de673fa97e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/ul/li</value>
      <webElementGuid>98409082-c471-4ea9-bd41-af9234c0c8ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'f29df585-b8d7-4d7b-8b5b-cd2bfba50e57' and (text() = 'Is equal to' or . = 'Is equal to')]</value>
      <webElementGuid>98755b1a-b2c9-457a-8a92-e8bc5cbae611</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
