<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Is equal to_1_2</name>
   <tag></tag>
   <elementGuidId>347885ee-e8ea-4326-aacf-9629fecca4c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='f8ac36ea-76d6-437b-b547-52905c491f3b']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#f8ac36ea-76d6-437b-b547-52905c491f3b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>6b65746b-2abc-43d2-be22-14bc9d79ec56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>2347e767-cc1a-425d-acd0-6460d3ddea70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>2760b0a9-4c6e-4cd2-a74f-534d103c740a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>4415cc29-5ad9-4ecf-a06e-28d38f57a7a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-list-item k-selected k-focus k-hover</value>
      <webElementGuid>c7587581-96dd-4d30-a29e-ea59efa85594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>34db6095-3c75-406f-8490-7fd553e6c1fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-offset-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dc5b4f92-fb35-400e-b5d6-b72e0de18fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f8ac36ea-76d6-437b-b547-52905c491f3b</value>
      <webElementGuid>b82ab694-4027-4aaa-8104-c6e95b250003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Is equal to</value>
      <webElementGuid>ffa6c991-630b-443a-a258-8dc49814680e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f8ac36ea-76d6-437b-b547-52905c491f3b&quot;)</value>
      <webElementGuid>f49ca61c-a6b2-4f86-b242-b47684aade3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='f8ac36ea-76d6-437b-b547-52905c491f3b']</value>
      <webElementGuid>f8585150-2a75-4de8-b41c-027be1f791d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='d8975e9f-7eac-49d5-8c8f-c5e8e2a479b5_listbox']/li</value>
      <webElementGuid>68ed2cb4-515e-48ab-aa23-5e1a335bf084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data found.'])[2]/following::li[1]</value>
      <webElementGuid>0610c929-2f00-4197-ad53-da71eaf61269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Processed Date'])[2]/following::li[1]</value>
      <webElementGuid>9f420887-f248-4f9d-8629-c9f854f33e31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is not equal to'])[2]/preceding::li[1]</value>
      <webElementGuid>5b07c9af-53bf-4cfe-98a9-3b90197a0831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/ul/li</value>
      <webElementGuid>245dc364-24a0-462a-88bb-43e53cb44004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'f8ac36ea-76d6-437b-b547-52905c491f3b' and (text() = 'Is equal to' or . = 'Is equal to')]</value>
      <webElementGuid>9fbd345d-9105-4c29-9c18-c0768ab295d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
