<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>scroll_to_delayed</description>
   <name>scroll_to_delayed</name>
   <tag></tag>
   <elementGuidId>e6e88988-c3a7-47f5-b1c9-4f8599bf5cd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@class='k-column-title'][normalize-space()='Delayed']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
