<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Delayed</name>
   <tag></tag>
   <elementGuidId>60727ff7-d5f8-4769-adf5-872e33c49bd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div//div//div//div//div//div//div//div//div//div//div//span[@class='k-input-value-text' and @xpath='1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.k-list-item.k-hover > span.k-list-item-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0a468a19-d482-4070-ac82-a6725df16c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-list-item-text</value>
      <webElementGuid>6b9dcbef-1dd4-4f07-94e2-17f5abb9d636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delayed</value>
      <webElementGuid>17e75f96-1a7b-453d-b868-b8e536cc6f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dd0ea2ed-327f-43ee-9d60-fa815533fc78_listbox&quot;)/li[@class=&quot;k-list-item k-hover&quot;]/span[@class=&quot;k-list-item-text&quot;]</value>
      <webElementGuid>8af702a1-5034-4c4a-b386-4a29e93fd5e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='dd0ea2ed-327f-43ee-9d60-fa815533fc78_listbox']/li[6]/span</value>
      <webElementGuid>03f7ab7b-12e1-43ec-9e63-4c9cbc9b95e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Created'])[3]/following::span[1]</value>
      <webElementGuid>4586de80-0317-4f78-b9ef-8a90c0d007c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date To Process'])[3]/following::span[2]</value>
      <webElementGuid>1cf8e818-24af-48e2-9e2a-c281ed7a1dbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Processed'])[3]/preceding::span[1]</value>
      <webElementGuid>1983bbf6-77f4-4e13-b0a8-2054d0212fd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error'])[3]/preceding::span[2]</value>
      <webElementGuid>896db96e-f99d-4250-89c2-7ea2dd81ad8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/ul/li[6]/span</value>
      <webElementGuid>f9bb35a1-ac84-4c27-95d9-c0061c7b4503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Delayed' or . = 'Delayed')]</value>
      <webElementGuid>9b75e2c5-855d-410b-8c3f-9af200619401</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
