<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login History</name>
   <tag></tag>
   <elementGuidId>3ef4c6c9-6c82-4f8a-b16a-460d5d6c3a61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='login-history']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#login-history</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f0c7de59-061a-4ba1-89fe-bb4d76885adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>b0ed7a05-a494-4c98-a6b2-315baa89bc87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-history</value>
      <webElementGuid>c0b0e35b-5161-41f9-9173-3bec83894e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Identity/Manage/UserLoginHistory</value>
      <webElementGuid>5a61c2cf-0808-48d7-aee1-dca64c21eb1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login History</value>
      <webElementGuid>2ae88636-c0db-4245-aae7-df39ca36d2d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-history&quot;)</value>
      <webElementGuid>14ceac4d-0b49-4aaa-aec7-fb74a121e879</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='login-history']</value>
      <webElementGuid>f4e34df2-5c62-4be5-b7b9-6d11d1073c79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-body-content']/div[3]/div[2]/div/div/ul/li[5]/a</value>
      <webElementGuid>f1dd977c-a6d2-4cd8-8eda-94a00f1a4b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login History')]</value>
      <webElementGuid>271b6f02-d3c3-4f55-90de-9cd2709a29f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal data'])[1]/following::a[1]</value>
      <webElementGuid>ec93997f-7b4e-402b-b406-b67243046438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Two-factor authentication'])[1]/following::a[2]</value>
      <webElementGuid>22295423-288a-4da5-ad16-731f1aca848f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal Data'])[2]/preceding::a[1]</value>
      <webElementGuid>aac54819-8daa-4eeb-8de9-0111fcea3d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[1]/preceding::a[1]</value>
      <webElementGuid>058baa61-ae25-47bb-a5f3-fa5d651b42d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/Identity/Manage/UserLoginHistory')])[2]</value>
      <webElementGuid>673465e9-e818-4f8a-94fd-ab121a4e0467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/ul/li[5]/a</value>
      <webElementGuid>3f2d5aa8-4f08-4657-b8e8-2f3a16802649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'login-history' and @href = '/Identity/Manage/UserLoginHistory' and (text() = 'Login History' or . = 'Login History')]</value>
      <webElementGuid>9d1c32f4-a81c-4970-b9a9-f29c7f997c78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
