<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_127.0.0.1</name>
   <tag></tag>
   <elementGuidId>8ec3ed14-be53-43bb-9bc3-1bb6784b5729</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='b3196d64-4cae-4b38-ad47-0afd2125c18c']/tr/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>38762596-4d3d-4041-96cf-8575dc9d8daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-table-td</value>
      <webElementGuid>f596e8e8-a6d9-4cc1-80c8-8b9bbdc918c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>149dc4d7-e191-4043-9086-382f15449b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>127.0.0.1</value>
      <webElementGuid>e16d49ef-08fd-4f4e-90a0-cc1d508285aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3196d64-4cae-4b38-ad47-0afd2125c18c&quot;)/tr[@class=&quot;k-table-row k-master-row&quot;]/td[@class=&quot;k-table-td&quot;]</value>
      <webElementGuid>1d4526d8-1b79-4e03-b724-6a729e599a50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='b3196d64-4cae-4b38-ad47-0afd2125c18c']/tr/td[2]</value>
      <webElementGuid>787ea4c8-224d-43cf-b491-e4990dbd8aa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kashyap.padhiyar@support.xcellence-it.com'])[1]/following::td[1]</value>
      <webElementGuid>84244c1f-a300-4442-bfa5-92035368761c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::td[2]</value>
      <webElementGuid>d7118cba-7520-49a3-917c-a16ebdd7a2f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::td[8]</value>
      <webElementGuid>bd4d7b16-bdb8-477b-bbcf-be5bbbe82d83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kashyap.padhiyar@support.xcellence-it.com'])[2]/preceding::td[11]</value>
      <webElementGuid>47441f59-1c20-4b27-98a6-6961f3f88acf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='127.0.0.1']/parent::*</value>
      <webElementGuid>c0d1fc9e-79f8-4c85-9cc9-05b048a70c15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>c5e4b517-9ce6-441f-ae86-289fbb485f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '127.0.0.1' or . = '127.0.0.1')]</value>
      <webElementGuid>0a8f4746-518c-44a6-9fd0-297b71692376</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
