<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_kashyap.padhiyarsupport.xcellence-it.com</name>
   <tag></tag>
   <elementGuidId>b9602503-2137-482e-b64c-48bfcf80206a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='b3196d64-4cae-4b38-ad47-0afd2125c18c']/tr/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.k-table-td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>c6468ac1-ce34-475e-a3d0-306c6281c8b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-table-td</value>
      <webElementGuid>16285841-0277-4287-bf3a-1044575c1e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>86ec1c9e-dac9-4c86-af52-abc498939a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>kashyap.padhiyar@support.xcellence-it.com</value>
      <webElementGuid>d8dc9b05-c559-43c3-9fbf-02fcb0fa9302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3196d64-4cae-4b38-ad47-0afd2125c18c&quot;)/tr[@class=&quot;k-table-row k-master-row&quot;]/td[@class=&quot;k-table-td&quot;]</value>
      <webElementGuid>5671c1b4-6019-4f7a-b5ea-7b54a1713b1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='b3196d64-4cae-4b38-ad47-0afd2125c18c']/tr/td</value>
      <webElementGuid>77b6fc36-31ac-4c5b-b5ee-403bb4dd5479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::td[1]</value>
      <webElementGuid>09abc573-141b-46ef-a1ef-407d94b63c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attempt Date'])[1]/following::td[1]</value>
      <webElementGuid>fc445faa-1937-46d7-a695-d91b160b501b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::td[9]</value>
      <webElementGuid>f1789d3f-ccff-44d4-8095-020fe4a4a085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kashyap.padhiyar@support.xcellence-it.com'])[2]/preceding::td[12]</value>
      <webElementGuid>1db4f8c4-32ee-499f-90c1-1c19c7690658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='kashyap.padhiyar@support.xcellence-it.com']/parent::*</value>
      <webElementGuid>1ba9ead5-23e9-4de2-abee-a9e0ddbe4217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td</value>
      <webElementGuid>1b22cdf6-28a9-41ed-910d-ceab8cc83641</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'kashyap.padhiyar@support.xcellence-it.com' or . = 'kashyap.padhiyar@support.xcellence-it.com')]</value>
      <webElementGuid>7b305ef9-362b-4db8-9603-1909896da85c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
