<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Re-Submit_1</name>
   <tag></tag>
   <elementGuidId>d3d3fc43-167a-48c0-9aaa-08cac0adc1a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datacell_0_0 > a.btn.btn-primary.btn-single-resubmit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@data-id='1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>59847195-d91d-4af8-8a8c-3bc6a5e5a2f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>afdbc213-aef5-4e37-8c57-03b4fc08b668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-single-resubmit</value>
      <webElementGuid>d4da7c91-7b70-4b8a-a58f-10c3281814dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5e047c02-dcab-41da-8288-7f26ca714bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Re-Submit</value>
      <webElementGuid>1ee7dd93-dc9b-4a78-bc9f-2126f9ef5d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbdc2a29-1839-4071-8195-5abf4f3d9100&quot;)/tr[@class=&quot;k-table-row k-master-row k-selected&quot;]/td[@id=&quot;datacell_0_0&quot;]/a[@class=&quot;btn btn-primary btn-single-resubmit&quot;]</value>
      <webElementGuid>6f377c0b-3497-4730-84c3-10e5131308e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//td[@id='datacell_0_0']/a)[2]</value>
      <webElementGuid>83976dcc-b178-4196-8046-bb3e39a12d6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Re-Submit')])[6]</value>
      <webElementGuid>700d9b8b-cdbe-4d74-ba00-438f18fbdec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Has Document'])[2]/following::a[2]</value>
      <webElementGuid>bbdc0335-8db4-424c-8698-304abb9d590b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Processed'])[2]/following::a[3]</value>
      <webElementGuid>12c3c728-4bac-408f-8df6-8d2c2330a72a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DOC10000000001'])[1]/preceding::a[1]</value>
      <webElementGuid>b5ccf887-9042-4a8f-95b0-7f73f596daaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TEC001'])[2]/preceding::a[1]</value>
      <webElementGuid>be7045ee-7e9b-44e2-803f-94e8c834aa0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[49]</value>
      <webElementGuid>4bd1e4c6-e168-47ef-ab0b-4afa25255f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div[2]/div[2]/table/tbody/tr/td/a</value>
      <webElementGuid>e9ff5c7f-b7b4-464f-8bc2-13e638c40a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Re-Submit' or . = 'Re-Submit')]</value>
      <webElementGuid>94eb1915-948b-4435-93e3-d2342ba38eef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
