<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Re-Submit_1</name>
   <tag></tag>
   <elementGuidId>d3d3fc43-167a-48c0-9aaa-08cac0adc1a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//td[@id='datacell_0_0']/a)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#datacell_0_0 > a.btn.btn-primary.btn-single-resubmit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>48278075-afaa-46ff-9870-907c3ab4275e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>a4c013aa-6471-45db-94b1-533808a75764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-single-resubmit</value>
      <webElementGuid>47c51bbb-aa9b-494b-a571-c0a518ecf6ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a08ea377-2b3b-44a3-988b-ebbe74ef3bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Re-Submit</value>
      <webElementGuid>68ae55b6-76d5-46a8-bcd0-b42b4309e8e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbdc2a29-1839-4071-8195-5abf4f3d9100&quot;)/tr[@class=&quot;k-table-row k-master-row k-selected&quot;]/td[@id=&quot;datacell_0_0&quot;]/a[@class=&quot;btn btn-primary btn-single-resubmit&quot;]</value>
      <webElementGuid>3aa526a2-35a6-4e7b-906e-16de468e6f35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//td[@id='datacell_0_0']/a)[2]</value>
      <webElementGuid>e707f017-fd75-47f8-acc2-cedfbc605e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Re-Submit')])[6]</value>
      <webElementGuid>8a0fc063-4d3b-432e-9b05-0c699ffe36be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Has Document'])[2]/following::a[2]</value>
      <webElementGuid>cc95342e-3c70-4801-a9ca-ba7120fb9032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Processed'])[2]/following::a[3]</value>
      <webElementGuid>4d273534-c2e3-4f63-8e83-686d3c7358d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DOC10000000001'])[1]/preceding::a[1]</value>
      <webElementGuid>94ae2ac4-9017-4c88-9cbf-b52626d4cfc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TEC001'])[2]/preceding::a[1]</value>
      <webElementGuid>608efdb5-e61d-45bc-834f-51a54f08c569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[49]</value>
      <webElementGuid>09ff571e-381d-401c-85e9-659e6bbf0272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div[2]/div[2]/table/tbody/tr/td/a</value>
      <webElementGuid>42dbb7d0-18de-4bf0-924a-bf646b33dc1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Re-Submit' or . = 'Re-Submit')]</value>
      <webElementGuid>6bd0dfa5-451d-4906-b88e-7b62258442d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
