<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_account_circle</name>
   <tag></tag>
   <elementGuidId>34917b11-4743-4ab9-8ce0-45f78bdc4188</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-bar-section']/div/div[2]/ul/li[3]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.user-profile-icon.show > i.material-icons</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>374963c1-cabe-4f6f-b0c4-7613f4afe7d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons</value>
      <webElementGuid>f21209d3-a1d9-4dd6-9339-a4fcfe4b106b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>account_circle</value>
      <webElementGuid>0dde4d78-1e04-4095-b0e9-99f95dce0375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-bar-section&quot;)/div[@class=&quot;page-header-inner&quot;]/div[@class=&quot;top-menu&quot;]/ul[@class=&quot;nav navbar-nav pull-right&quot;]/li[@class=&quot;dropdown dropdown-user&quot;]/a[@class=&quot;user-profile-icon show&quot;]/i[@class=&quot;material-icons&quot;]</value>
      <webElementGuid>717ad50d-22dd-45cc-b542-4aa75c618ecb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-bar-section']/div/div[2]/ul/li[3]/a/i</value>
      <webElementGuid>76842d59-3659-487e-911f-b958f8a5004c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All notifications'])[1]/following::i[1]</value>
      <webElementGuid>f700074a-4d92-4cb4-9279-5d34a91922e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications'])[1]/following::i[1]</value>
      <webElementGuid>e994bc59-e773-4c4b-8d98-762022c686e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='account_box'])[1]/preceding::i[1]</value>
      <webElementGuid>43bc04cf-47a3-4fcb-84f1-58104f0ecf00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='account_circle']/parent::*</value>
      <webElementGuid>16262675-ff1d-4664-b94d-09b30b9bd310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[3]/a/i</value>
      <webElementGuid>1d2d2d02-ae82-4bf8-b31d-6434a223093a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'account_circle' or . = 'account_circle')]</value>
      <webElementGuid>82d1424a-3641-46e2-9ff4-00ed6ac56435</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
