<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Has Document_k-select-checkbox k-chec_bdcdac_1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>6c545982-8b88-4edf-a8e5-b16322409ef1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[10]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#grdDelayedExportQueues > div.k-grid-container > div.k-grid-content-locked > table.k-grid-table.k-table.k-table-md.k-selectable > tbody.k-table-tbody > tr.k-table-row.k-master-row > #locked_datacell_2_0 > input.k-select-checkbox.k-checkbox.k-checkbox-md.k-rounded-md</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>876072f0-c64f-4814-bf31-68eb474432a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>5d5e3c89-2475-46de-9193-d95ec9e731ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-select-checkbox k-checkbox k-checkbox-md k-rounded-md</value>
      <webElementGuid>ff761173-8c9c-41de-b4ca-f15b40440e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6589d4d8-9372-486e-bdca-bd5743762a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select row</value>
      <webElementGuid>15badc5e-c5c0-466d-a007-e51a7ea49456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>64f110ab-ce4c-4c15-a2ed-c69f28597437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f3f9c376-bf5b-4d1c-9e1a-467ae8e735df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grdDelayedExportQueues&quot;)/div[@class=&quot;k-grid-container&quot;]/div[@class=&quot;k-grid-content-locked&quot;]/table[@class=&quot;k-grid-table k-table k-table-md k-selectable&quot;]/tbody[@class=&quot;k-table-tbody&quot;]/tr[@class=&quot;k-table-row k-master-row&quot;]/td[@id=&quot;locked_datacell_2_0&quot;]/input[@class=&quot;k-select-checkbox k-checkbox k-checkbox-md k-rounded-md&quot;]</value>
      <webElementGuid>c48d89bf-e4ba-4c62-b5ca-c9e4596db344</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[10]</value>
      <webElementGuid>92edb918-17de-430e-8f82-35e6d8ae85e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//td[@id='locked_datacell_2_0']/input)[2]</value>
      <webElementGuid>08f12fa5-8106-4045-bf42-824f136bfe6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div[2]/div/table/tbody/tr[3]/td/input</value>
      <webElementGuid>4c498668-df53-4ae6-9589-fa21c9bcb748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>7886b9d2-0037-445b-b614-979d2f06e059</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
