<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Has Document_k-select-checkbox k-chec_bdcdac_1</name>
   <tag></tag>
   <elementGuidId>6303516b-55b6-4738-a578-faf39e16ef31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#locked_datacell_1_0 > input.k-select-checkbox.k-checkbox.k-checkbox-md.k-rounded-md</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56911971-3428-4556-b2ea-6da91db22013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ca0c0fbd-3d72-4e41-9ea3-83b25b23ced4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-select-checkbox k-checkbox k-checkbox-md k-rounded-md</value>
      <webElementGuid>03a3a2c7-9bcc-4a38-811f-a51b90510159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e787ddfa-7f0f-470d-97a1-011b720e3e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select row</value>
      <webElementGuid>6de45d01-245e-4d01-b065-aa0d1d1c299e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c0648f04-82f0-44a7-95c4-a3ae59ad7e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b8e6825b-f12e-40f2-b92e-667352419c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grdExportQueues&quot;)/div[@class=&quot;k-grid-container&quot;]/div[@class=&quot;k-grid-content-locked&quot;]/table[@class=&quot;k-grid-table k-table k-table-md k-selectable&quot;]/tbody[@class=&quot;k-table-tbody&quot;]/tr[@class=&quot;k-alt k-table-row k-table-alt-row k-master-row&quot;]/td[@id=&quot;locked_datacell_1_0&quot;]/input[@class=&quot;k-select-checkbox k-checkbox k-checkbox-md k-rounded-md&quot;]</value>
      <webElementGuid>6bc4ac35-85d2-4dd7-a178-f2d5a255c501</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[3]</value>
      <webElementGuid>77fb6032-cef8-4337-9470-5f1cc3db8b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='locked_datacell_1_0']/input</value>
      <webElementGuid>1baf2a5b-96d5-47b0-b4f1-3f7c1737dde6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/input</value>
      <webElementGuid>530dbe5f-8599-4401-83a0-31eee1f38eca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>d39261c9-547e-4055-9b4d-b83074e2dd43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
